### ISSUE TITLE
Add code to convert diacritic entities to their unicode selves

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#105]
_From @TheMightyBuzzard on October 13, 2014 12:30_

We could write a sub that checks the entities themselves for a max of four but we already have a very nice and quick sub doing that for their proper unicode encoded selves, so just convert them to unicode before the diacritics_max op happens.

_Copied from original issue: SoylentNews/slashcode#360_

**Comment by TheMightyBuzzard** [comment]
This should have been closed long ago. Unless I'm on more drugs than usual, I remember it being long since done.
