### ISSUE TITLE
When returning to a story, highlight any new comments

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#118]
_From @Open4D on May 12, 2014 22:53_

Feature request:

Allow users to opt in to have their story viewing tracked - so that you know which comments they have already (potentially) read.  If they visit the same page of comments again, highlight any new comments - perhaps in a different colour.  (Or perhaps the new comments should be 'normal' and the old comments should be in a different colour.)

For performance reasons, you might want to only remember the 50 most recently visited stories, per user, or something.

You might want to implement this not just for comments that are *new*, but also for comments that haven't been loaded yet by that user for any other reason - e.g. if the user has just lowered his/her threshold, or if a comment has been modded up to reach the user's threshold.

(Credit [to kaszz](http://soylentnews.org/comments.pl?sid=1790&cid=42357).)

_Copied from original issue: SoylentNews/slashcode#179_

**Comment by paulej72** [comment]
_From @NCommander on May 13, 2014 0:23_

Hrm, we *could* store a timestamp of last time a user hit article.pl in the database (there's already a key/value table for random variables), where we could put viewed_sid_when, and then colorcode off that; would tie nicely in with the improved threading (probably only make it available in that mode since it won't play nicely with the older setup).

We'd likely have to store the value in memcache for performance reasons, but definately doable.

**Comment by paulej72** [comment]
_From @zenbi on May 13, 2014 10:18_

<a href="http://pipedot.org/story/2014-05-13/read-it">Implemented</a> in <a href="https://github.com/pipedot/pipecode">Pipecode</a>.

**Comment by paulej72** [comment]
There is some crap for this from the D2 system.  I purged some of it already as it would not have worked for our system.

using a timestamp would work nicely, and i think there is a place in the db that we can use for that,just not sure that storing the value in memcache will be appropriate as that value will be changing all of the time.

**Comment by paulej72** [comment]
_From @mrcoolbp on September 1, 2014 17:53_

I think this would be rather useful, can we look at this again?

**Comment by paulej72** [comment]
_From @TheMightyBuzzard on September 1, 2014 18:10_

Sounds interesting enough but ima leave it to PJ as my plate's fairly full at the moment with cryptocoin and as much low hanging fruit as I can find.

**Comment by paulej72** [comment]
_From @Jaruzel on September 3, 2014 14:21_

Reddit does this for Gold subs. Maybe make it a subscriber only perk ?

**Comment by TheMightyBuzzard** [comment]
Made moot by #273

**Comment by TheMightyBuzzard** [comment]
or was it one of the previous ones?
