### ISSUE TITLE
"No discussion or comments found for this request"

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#119]
_From @Open4D on May 13, 2014 12:40_

Sometimes I type out a comment, click "Preview", and get a page with the following message:
*No discussion or comments found for this request. To create your own discussion, please use journals.*

Luckily I can just click my web browser's back button, and it takes me back to the comment entry page, and it remembers the text that I had typed out.  I then click "Preview" again and it works as normal.

I've probably encountered this less than 10 times, and probably only in the last few weeks.  Most recent was at 2014-05-13T09:45Z.  I saved the HTML, in case it's of any use.

_Copied from original issue: SoylentNews/slashcode#180_

**Comment by paulej72** [comment]
_From @Open4D on May 16, 2014 9:59_

I got this again just now - specifically at 2014-05-16T09:54Z.  This time I think it was after I had pressed "Submit".

**Comment by paulej72** [comment]
_From @Open4D on May 16, 2014 20:43_

Another one, at  2014-05-16T19:02Z, after pressing "Preview".  So I pressed "Back", previewed again, submitted successfully ([this comment](http://soylentnews.org/comments.pl?sid=1871&cid=44349)).

**Comment by paulej72** [comment]
_From @tathra on May 17, 2014 22:19_

i'm getting this one too.  seems to be tied to how the site keeps randomly logging me out and back in with refreshes.

**Comment by paulej72** [comment]
Reskey?

**Comment by paulej72** [comment]
_From @Open4D on June 2, 2014 12:59_

2 more occurrences:
* 2014-05-22T13:43Z
* 2014-06-02T12:32Z

I don't know what "reskey" is, but I am fairly confident that this error is not correlated with taking a long time to make a post.

I don't remember exact details, but a typical scenario might be:
* Click "Reply" on a comment
* spend 5 - 10 minutes composing the reply
* click "Preview" (successfully)
* spend 1 minute making corrections
* click "Preview"
* get the error
* click the back button
* click "Preview" again straight away (successfully)
* spend 20 seconds re-reading it, one last time
* click "Submit" (successfully)

**Comment by paulej72** [comment]
Can someone let me know what network you are using to connect to SN when you are having these issues.  We have seen this problem when the users ISP switches exit points randomly.  It can be seen when using mobil connections as the cell network seems to route the users connection randomly to different exit ip addresses which break not only the reskey system but also the login cookie depending on the users cookie settings.

The reskey system is used to keep track of which form is submitted by which user and to do some anti-spam stuff by limiting how fast a user can submit forms and by monitoring connections from different ip addresses.

**Comment by paulej72** [comment]
_From @Open4D on June 12, 2014 9:37_

1. I was at my desk at work, connected to a large corporate network with a LAN cable.
2. Went [here](http://soylentnews.org/article.pl?sid=14/06/11/2315249&amp;from=rss)
3. Read it, and composed my comment in a text editor
4. Refreshed the page to check for new comments
5. Clicked reply
6. Pasted in my comment
7. Spent a minute or two checking / making changes / previewing
8. At about 2014-06-12T09:01Z I pressed "Preview" again and got the error
9. Pressed the back buton.  Firefox had remembered the text of my comment.
10. Pressed "Preview" again. It worked
11. Pressed "Submit" and it worked: http://soylentnews.org/comments.pl?sid=2319&cid=54493

**Comment by paulej72** [comment]
_From @Open4D on March 13, 2015 17:32_

I don't remember getting this in a long time.  What about you @tathra ?  Shall I close this?

**Comment by paulej72** [comment]
_From @TheMightyBuzzard on March 13, 2015 18:55_

Nah, I've gotten it recently. Seems to only happen if you leave tabs open for days on end or through several restarts of the server though.

**Comment by TheMightyBuzzard** [comment]
Going to close this for now as we've had no reports of it in over a year.
