### ISSUE TITLE
Logged out and back in with no action other than reload

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#121]
_From @agilbertson1977 on June 2, 2014 22:35_

18:27 < AndyTheAbsurd> so I reloaded the website not long before I left for work this morning, and it showed me as not being logged in
18:27 < AndyTheAbsurd> but I reloaded again a couple of minutes ago (after I got back from work) and now I'm logged in again
18:27 < AndyTheAbsurd> so...I guess there's something funky going on with the login code?
18:28 < TheMightyBuzzard> very possible
18:28 <@paulej72> more likely the login cookie madness
18:28 < AndyTheAbsurd> probably a known bug, then?  Do you want any info from me to help locate/debug the issue?
18:30 <@paulej72> AndyTheAbsurd: not an issue that sepcifically heard before. you can file an issue on github if you want.

So I filed this bug.  No idea what's going on; I wasn't doing anything strange, I didn't take any unusual browser actions or restart the browser or restart my computer...just...not logged in the morning, figured my previous login had expired and I would log in again when I got back, got back 10 hours later, reloaded the page to read the newest stories and BOOM I was logged in again.

_Copied from original issue: SoylentNews/slashcode#216_

**Comment by paulej72** [comment]
_From @NCommander on June 16, 2014 6:35_

Login is known to be wonky for some users, though it isn't clear why. Basic SAN check, please make sure your login limitations are set to Everywher vs. Subset (its on the change password scren). Markng this one high priority

**Comment by paulej72** [comment]
Some of the issues recently may be due to gluster our back end system that syncs the slash directories among the different servers.  We have been having issues where the servers loose their link to bluster and if the frontend that you are on goes down, you have a bit of connection issues with the running server and it seems to require a re login.  At least that is what I was seeing one of the times that gluster took a dump.

**Comment by paulej72** [comment]
I wonder if this is still and issue.  I think we still need to have memcache load in in the logintokens from the db if the service is restared

**Comment by TheMightyBuzzard** [comment]
I haven't seen any login issues unless the server had just been bounced in a long time. Closing until someone reports it's still happening.
