### ISSUE TITLE
Images in story submission

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#124]
_From @lhsi on June 24, 2014 12:47_

[Feature request]

What are the thoughts of allowing images in a story submission? Not as something to include all the time, but I think some would be enhanced by it. 

I have submitted a couple of stories and thought it would have benefited from showing one of the graphs used, or if something is new or unusual (for example, I recently submitted a story about a new species of dinosaur but had no way to include the image of what it might have looked like). 

Maybe if an image is included, it is after the "Read More" break to stop it appearing on the main page. 

_Copied from original issue: SoylentNews/slashcode#231_

**Comment by TheMightyBuzzard** [comment]
Editors can already do this, can't they?
