### ISSUE TITLE
Nagger doesn't update after submission

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#131]
_From @lhsi on August 18, 2014 13:18_

The nagger doesn't update after a submission, you need to go to a new page to see the new total. 

Step to reproduce: Submit an article submission when there are less than 20 stories in the queue (so the nagger line appears at the top of the page). You are taken to the "Submission received" page (the one that confirms that the submission was received). 

Expected: The "Number of stories in the queue" has gone up by one with a new story
Actual: The number remains unchanged. Going to a new page has a new number

Workaround: Go to a new page to see the updated number. 

_Copied from original issue: SoylentNews/slashcode#281_

**Comment by paulej72** [comment]
That has to do when certain parts of the page are generated in slash.  For some reason most pages the header code is all rendered, before the perl is run that does the current operation.  In your case it is the submit a new story.  This is done after the header is rendered so the nagger gets a stale value.  It is the same reason you need to click on a new page to  see a theme change after saving the theme preference.

This would require a major overhaul to slash to fix.

**Comment by paulej72** [comment]
_From @lhsi on August 19, 2014 13:28_

As mentioned, this is not a major issue, so feel free to reject if it is not worth the work (I guess it could be done as part of a major overhaul, if an overhaul is being done for another reason)

**Comment by TheMightyBuzzard** [comment]
Is "I don't really care enough to totally rearrange page rendering order" a good enough reason to close this?

**Comment by TheMightyBuzzard** [comment]
Yeah, I really think it is.
