### ISSUE TITLE
DDNS for subscribers

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#133]
_From @TheMightyBuzzard on August 20, 2014 13:43_

Was looking at dynamic dns for some reason the other night and it struck me that this was one thing we could offer subscribers without too much hassle. Very low traffic, very low disk space, very low processor time, ideally zero maintainance, moderate value. Thoughts?

They may need to be hosted under a subdomain of course to prevent confusion with official servers.

_Copied from original issue: SoylentNews/slashcode#294_

**Comment by TheMightyBuzzard** [comment]
With us using LE certs, this would best be hosted under sylnt.us.

**Comment by TheMightyBuzzard** [comment]
Discussed among staff and discarded for both security and practical reasons.
