### ISSUE TITLE
User to User Messaging

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#136]
_From @TheMightyBuzzard on August 25, 2014 3:0_

What the title says. It would be bloody nice to be able to drop a message to a friend without having to offtopic under an article or their journal.

_Copied from original issue: SoylentNews/slashcode#307_

**Comment by paulej72** [comment]
There may be some messaging system already in place in the code.  I have seen references to it, but I have not looked for it directly.

**Comment by TheMightyBuzzard** [comment]
We could do it easily but the community responded with a resounding "meh" when asked if they wanted it. Go away, little issue.
