### ISSUE TITLE
Submission Categories Rework

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#138]
_From @TheMightyBuzzard on August 28, 2014 11:54_

We run enough political stories that we should probably include a Politics category at the very least. It's been suggested on IRC that categories could even use a more thorough rework. This ideally needs a half hour to an hour of suggesting and arguing at a staff meeting to hammer out.

_Copied from original issue: SoylentNews/slashcode#319_

**Comment by paulej72** [comment]
_From @lhsi on September 15, 2014 10:36_

"Space" and "Health" would be interesting categories, there are probably enough stories on both to warrant their own section instead of "Science", which is pretty broad. Interestingly there isn't an "Internet" or "Network" category. Would "Legal" be a new section, or could it be "Politics/Legal" (for example, for copyright issues in the news)?

(Side note: I am generally against purely political stories; most of them are just USA politics which excludes the rest of the world, and most of the time they just end up being shouting matches in the comments)

**Comment by paulej72** [comment]
Politics is waiting for nexus support, which is waiting for wildcard cert.  Will need to add some topic icons for these as I deleted some of the unused ones when I did the latest topic icon updates.

**Comment by paulej72** [comment]
_From @mrcoolbp on April 24, 2015 15:58_

I recommend "Breaking News" as a topic

**Comment by paulej72** [comment]
_From @mrcoolbp on April 24, 2015 16:0_

We'll need to get some new icons as P.J. mentioned, so once we have a list of topics we like, let me know and I'll see if our icon guy wants to do some more work.

**Comment by TheMightyBuzzard** [comment]
I think we've done everything in here. Closing.
