### ISSUE TITLE
Non-Meta-Moderation Refresh

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#139]
_From @TheMightyBuzzard on August 28, 2014 12:2_

We're more or less running stock slashdot categories for moderation. I'd like us, prior to work going into m2 (#278), to sit down and have a discussion of what moderations need the axe, which should stay, and what new ones we want to include. This doesn't need to be done via dev fiat though, it should be argued at in a staff meeting and either decided by the CEO or delegated to the User Experience team lead.

_Copied from original issue: SoylentNews/slashcode#320_

**Comment by TheMightyBuzzard** [comment]
Closing. It's become apparent that we prefer the incremental approach over all at once.
