### ISSUE TITLE
there's a double & entity encoding in atom feed

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#140]
_From @crutchy- on September 1, 2014 20:15_

<title type="html">American Values &amp;amp; Chinese Students</title>

_Copied from original issue: SoylentNews/slashcode#325_

**Comment by paulej72** [comment]
_From @TheMightyBuzzard on September 1, 2014 20:41_

Yeah, I know. It annoys the crap out of me.

**Comment by paulej72** [comment]
_From @TheMightyBuzzard on October 1, 2014 13:45_

Temporarily fixed in pull request #341. Do not close this issue.

**Comment by TheMightyBuzzard** [comment]
You know what? After two years I'm calling the temporary fix permanent unless someone else wants to play with something that works.
