### ISSUE TITLE
'_pk_ref.1.2d83'  cookie contains http_referer URL. Possible breach of privacy.

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#141]
_From @Jaruzel on September 3, 2014 14:6_

Athough it is accepted that HHTP web logs can catch the referring url of a page request, it also seems that Slashcode is grabbing it and at the very least sending it back to the user as a cookie (_pk_ref.1.2d83) - Is this required, and what else is slashcode doing with it?  

From a privacy point of view, it could expose users browsing habits.

_Copied from original issue: SoylentNews/slashcode#327_

**Comment by paulej72** [comment]
_From @TheMightyBuzzard on September 12, 2014 1:57_

I won't swear to it but I'm pretty sure that particular cookie is part of the system to keep users on either http or https, depending on what the last link they came from was. It's somewhat difficult to do when your webservers are directly behind a load balancer that https connections terminate and become http connections at.

**Comment by paulej72** [comment]
_From @NCommander on September 12, 2014 12:13_

I think this is set by the load balancer and not slashcode. I haven't seen
it on Dev or locally but some one can double check

**Comment by TheMightyBuzzard** [comment]
Whatever it was set by before, it's not set now. Closing.
