### ISSUE TITLE
Enhancement(s) for "recently" accepted submissions

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#146]
_From @Open4D on October 28, 2014 14:23_

At the bottom of each user page is a "Recently Accepted Submissions" section.  It is not clear how the list of accepted submissions is being limited based on how recent they were.

Example with 386 submissions: http://soylentnews.org/~lhsi/

Perhaps the text should say "Showing **all** 386 submissions" or "Showing all submissions in the last 12 months" or something, to help reflect whatever the actual limits are?

(As a long term change - actual code rather than just wording - perhaps it should be limited to the most recent 50 submissions, with only subscribers getting access to the older blocks of 50?)

_Copied from original issue: SoylentNews/slashcode#377_

**Comment by paulej72** [comment]
_From @TheMightyBuzzard on October 28, 2014 16:34_

That's a fair point. For subscribers I think they ALL show but I'm not sure how we decide for non-subscribers. We can probably stand to clarify both cases.

**Comment by TheMightyBuzzard** [comment]
We've long since done this, no? Closing.
