### ISSUE TITLE
Smartmatch error on restart of apache

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#15]
Get this error when restarting apache:

Smartmatch is experimental at /srv/soylentnews.org/perl/lib/perl5/site_perl/5.20.1/Slash/Slashboxes.pm line 63.

**Comment by NCommander** [comment]
It's generated by a CPAN library as far as I can tell. This error was likely generated on slashcode as well, but supressed since shit didn't get written out to STDOUT on startup. Honestly, this is one of those rare cases where I think we should plug our ears and ignore it.

**Comment by NCommander** [comment]
Ugh, I took a deeper look at this, and its actually perl itself throwing that warning: http://www.perlmonks.org/?node_id=1039456

That's not going to be fun to fix.

**Comment by paulej72** [comment]
I wonder how many cases we have of the smartmatch feature.  If a few, we should be able to rewrite.

**Comment by TheMightyBuzzard** [comment]
Closing until it creates an actual bug instead of just a warning.

**Comment by NCommander** [comment]
It's a compatibility issue in Perl unfortunately. We'd have to rewrite a
large chunk of code unfortunately.

On Tue, Sep 27, 2016 at 11:18 AM, TheMightyBuzzard <notifications@github.com
