### ISSUE TITLE
Editing: Post-edit time ripple

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#156]
_From @chromatos on March 15, 2015 21:16_

When inserting a story, there could be a button + edit field to ripple the publish times of later stories. The edit field is for a time offset (or just snap it to the next hour or whatever).

_Copied from original issue: SoylentNews/slashcode#430_

**Comment by marty-b** [comment]
That sounds like an excruciatingly useful idea. =)
I like the concept but fear the problem solution needs better fleshing out than to 'make subsequent stories' release date/time stamp 'correct'".
For example, we have has meta stories by NCommander in the queue that are slated to go out at a specific time; rippling publish times would throw that off.
I would advocate for directly-editable publish times on the story list page, with a check/warning if that story is currently being edited. (Isn't there already code to highlight currently-being-edited stories in the story-queue list when in the story editing page?)

**Comment by TheMightyBuzzard** [comment]
Superseded by #416. Closing.
