### ISSUE TITLE
Story Admin/List on Story Preview shows old stories, not latest

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#159]
_From @soytakyon on April 15, 2015 3:39_

If you are editing a story, the Story Admin list on the right-hand column only shows up to 3 stories after the story you are editing. So if I edit the "Linux 4.0 Debuts with the Usual No Fanfare" story, I can see up to "NSA's Grand Plan". I think we want the latest 15-20 stories from the Story List instead.

_Copied from original issue: SoylentNews/slashcode#442_

**Comment by TheMightyBuzzard** [comment]
Looks like we did this a long time ago. Closing.
