### ISSUE TITLE
Implement user/submissions page

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#165]
_From @soytakyon on May 12, 2015 20:29_

http://soylentnews.org/~username/submissions

Feature request: Show a list of user submissions, and nothing else, on these pages.

_Copied from original issue: SoylentNews/slashcode#450_

**Comment by soytakyon** [comment]
Now I don't actually see all of my submitted stories on my user page when logged in (I did before). The "recent" cutoff is seemingly 1 year for this listing.

Another reason to have a ~username/submissions page simply listing every submission and nothing else (comments, moderations, etc.)

**Comment by TheMightyBuzzard** [comment]
This got done but not closed.
