### ISSUE TITLE
Meta Moderation M2.

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#169]
_From @paulej72 on August 15, 2014 15:13_

We need to get the M2 system working for our site.  The community has stated that ./ M2 system has many issues and therefore should not be implemented as is.

What we need to do is list the issue with the current system here and also list what we propose to fix these issues.

This is going to be a major improvement to the site, so lost of thought should go into how this works.

_Copied from original issue: SoylentNews/slashcode#278_

**Comment by paulej72** [comment]
_From @TheMightyBuzzard on August 17, 2014 16:19_

The original vision was:

* Drastically reduce number of moderators
* Return of meta-moderation
* Allow more moderation with fewer moderators
* Supermoderations to lock posts that need it

There was a bloody lot of discussion on this but I the latest conversation was something along the lines of:

* Downmods are the most abused and therefore in most need of protection against.
* Non-expiring modpoints, replenished hourly.
* Report button for bad mods.
* Suggestion to lock moderation after admin intervention.
* Supermoderation.
 * Concerns about supermoderation creating an elite class.
 * Debate on whether supermods should be up-only or also down-capable.
 * Debate on supermods locking posts vs having infinite points until expired.
* Suggestion to force surfing at -1 while you have modpoints.
 * Was fairly unpopular.
* Reexamine moderation categories.
 * Suggestion to remove under/overrated entirely.
 * -1 Factually Incorrect type mod
* What should the standards be for m2 elegibility?
* Separate score for agree/disagree suggested and NC approved.
* The logic grid I suggested for upmods/downmods. Will redetail below.

There has also been plenty of discussion on IRC about this but that is just too many logs to grep through without a good regex.

**Comment by paulej72** [comment]
_From @TheMightyBuzzard on August 17, 2014 16:51_

Short and simple of m2 vs a mod logic grid I suggested was something along the lines of bad upmods and good downmods do not influence your m2 score but bad downmods and good upmods do. 

I'd further suggest either splitting +m2 scores and -m2 scores into different vars, or weighting -m2 scores to -10 vs a +1 for up +m2 scores. Bad downmods are much more a problem than bad upmods. -1 Disagree is pretty rampant.

I'm also in favor of completely reworking moderation categories. Under/Overrated can completely go IMO. We either need a reason to up/downmod a comment or it should keep its current score.

I'm not really digging the idea of supermods locking posts. Giving them infinite modpoints and letting m2 take care of bad downmods would be better as it lets the bad downmoders hang themselves and fall out of the moderator pool.

I'd also like to implement a check for modbombs. Multiple (3+) downmods to a single user's comments on any given day should (temporarily the first time, permanently if the behavior continues) remove the user from the moderation pool and invalidate the moderations. This may need to run as a slashd job; I can't see this being an inexpensive enough operation to preform before a page load can be completed.

**Comment by paulej72** [comment]
_From @Al-Hunt on August 17, 2014 20:49_

Please explain how meta-moderation works. I understand it to be moderating the moderator - in other words, the meta-moderator looks at a previous moderation and says it was a fair or unfair moderation. Do I understand it correctly? If so, I'm all for it. 

Also, I agree totally that moderators should be concentrating on upmods except in cases of blatant crap. Upmodding posts will bury the mediocre ones and encourage discussion.

Great to see moderation in general getting so much attention.

**Comment by paulej72** [comment]
_From @TheMightyBuzzard on August 17, 2014 22:18_

Exactly like that. What's undecided are the specifics like who gets to meta-moderate, when, and what/how much effect each meta-moderation will have.

**Comment by soytakyon** [comment]
Maybe users should have a dev-like playground where they can troll each other and test the metamoderation features and moderation system change before they are finalized and rolled out on prod.

**Comment by NCommander** [comment]
I fixed the M2 code awhile ago, though the current moderation algrothim
doesn't take the m2 values into account.

**Comment by TheMightyBuzzard** [comment]
Closing. Every discussion we've had on this, the consensus was of the "no meta-mod for us" variety.
