### ISSUE TITLE
dead link on main page: humans.txt

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#172]
There is a link to a non-existent file on the main page of the site: humans.txt

NOTE: I was trying to verify that all links provided on the main page were valid.  I had previously had great success using a link-checking utility called Xenu link sleuth which runs on Microsoft Windows and can be downloaded from: http://home.snafu.de/tilman/xenulink.html

1.) Ran Xenu link sleuth[*] on https://soylentnews.org/ with max depth of 1, with cookies enabled, and added an exclusion to NOT check this link: https://soylentnews.org/my/logout
2.) Waited for it to spider through 190 links
3.) Accepted offer to generate report
4.) Found one link to a non-existent file.  Source html from the main page is:
   &lt;link type="text/plain" rel="author" href="//soylentnews.org/humans.txt" /&gt;
5.) Confirmed issue by loading the main page in a browser (pale moon) and doing a view source.

**Comment by paulej72** [comment]
NCommander must have deleted it.  xlefay originally added it and its a bit out of date.

**Comment by TheMightyBuzzard** [comment]
References removed in #302
