### ISSUE TITLE
heavily nested comments result in single-char-wide lines in narrow browser window

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#174]
When viewing a story thread which has highly nested comments while using the browser on my mobile (resolution: 320x240), at a depth of something like 7 or replies, the text gets wrapped down to a single character per line.  This makes it a bit difficult to follow the conversation.

Would appreciate having a minimum of at least 5 chars displayed per line no matter how deeply nested the comments are.

Might be able to use min-width in the CSS to make it happen?

**Comment by paulej72** [comment]
Fixed in my next pull
