### ISSUE TITLE
RFE: Automagically insert 'Original Submission' link at end of submission text in 'Intro Copy' area

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#175]
The Editors seem to have settled on a working format/style for referring to the original submission to a story.

1.)  The simple case is when one submission results in a single story.  In that case, we insert text of the form:
`<hr> <small> <a href="https://soylentnews.org/submit.pl?op=viewsub&subid=7810">Original Submission</a> </small>`

The only thing that varies is the value for the subid.

2.) A slightly more complicated case is when we have merged two (OR MORE!) stories, then we'd have:
`<hr> <small> <a href="https://soylentnews.org/submit.pl?op=viewsub&subid=7810">Original Submission #1</a> <a href="https://soylentnews.org/submit.pl?op=viewsub&subid=7811">Original Submission #2</a></small>`

It is tedious and error-prone to have to type this into every story we push out onto the site; the link to the original submission is presented in the story editor screen just a short ways above the 'Intro Copy' area.

**Comment by soytakyon** [comment]
The way editors are inserting it usually adds an extra closing `</p>` tag after the `</small>`. To prevent this `<hr> <small> <a href="https://soylentnews.org/submit.pl?op=viewsub&subid=0000">Original Submission</a> </small>` should be inserted into the end of the last paragraph element, if there is one, or a new paragraph, if `</blockquote>` is the last closing tag.

**Comment by paulej72** [comment]
fixed in #202
