### ISSUE TITLE
Signoff list disappears in story edit after preview

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#176]
If I go in to edit a story that has already been put out into the story queue, and has already been second-edited, (so there's at least two different people on the signoff list), and then make a change and hit preview, I've see the signoff list change to 'No Signoffs'

This has been around for at least a few weeks.  Not sure when it first appeared.

Work around is to save the changes, and then go in to edit the story again; Signoff List gets repopulated.

**Comment by paulej72** [comment]
Got it fixed.  stoid was not set properly on previewing. Will be in my next pull.

**Comment by paulej72** [comment]
Fixed in #179
