### ISSUE TITLE
Need to fix topic tasks and topic picker

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#18]
The topic section system is generated from a slashd task that builds the necessary files from what is in the topics table.  With rehash going full dynamic, we need to make the system work with the current file updates, or make the topic selection much easier to do. 

One way to do this is using a table with multiple checkboxes, but we would need to determine if order is important for multiple topic and nexus selection.

The current section system allows for multiple sections and order to be set relatively easily, but requires a javascript widget.

**Comment by paulej72** [comment]
Topic picker is also broken for nexus.admin.pl.  not sure why it is, but if we remove topic picker, this will reduce the need for the topic task.

**Comment by paulej72** [comment]
Fixed topic picker in pull #35

**Comment by NCommander** [comment]
I took a stab at this and failed to fix it. The entire popup tree is generated by a perl module that is third party, and I can't figure out how its supposed to work. I'm not sure this is a real blocker, the admin*js/css files will only change if we change the topics, and we can manually run rsync in that rare case.

**Comment by NCommander** [comment]
Order is used for determining the order it shows up on, as well as some edge cases with nexus supersedence. IMHO, I'm not sure its THAT important to perserve that functionality. Maybe just have a manual field where you type in the weight ...

**Comment by TheMightyBuzzard** [comment]
We took care of this long ago unless I'm thinking it's something else.
