### ISSUE TITLE
Touche gets messed up in messages

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#182]
![screen shot 2015-06-17 at 8 18 43 pm](https://cloud.githubusercontent.com/assets/6743611/8221579/45f0bb3e-152e-11e5-8ad8-dfa7704d32af.png)
Here it is in all its gory detail.

**Comment by TheMightyBuzzard** [comment]
This may be fixed. Needs tested.

**Comment by TheMightyBuzzard** [comment]
Verified does not exist anymore.
