### ISSUE TITLE
Fortune not updated in over 24 hours

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#186]
1.)  The 'fortune' which appears at the bottom of the main page on production seems to be stuck.  For the past 24 hours or so, I've seen this fortune displayed:
'This here's the wattle, The emblem of our land. You can stick it in a bottle; You can hold it in your hand. Amen! -- Monty Python'
2.)  Loading a selection of stories from the main page shows the same fortune at the bottom of those pages, too:
https://soylentnews.org/article.pl?sid=15/06/24/0252208
https://soylentnews.org/article.pl?sid=15/06/24/0248254
https://soylentnews.org/article.pl?sid=15/06/23/1849217
3.) Also saw the same fortune appear at the bottom of a user's journal page:
https://soylentnews.org/~throwaway28/journal/

**Comment by paulej72** [comment]
fortune not installed on helium.  It has been installed and motd updated.
