### ISSUE TITLE
Script injection via URL encoding.

### ISSUE THREAD

**Issue by VortexCortex** [SoylentNews/rehash#187]
Pasting the following into a comment will allow arbitrary HTML (including Javascript) to be injected by users.

`<a href="https://%76%63/%22%3E%3Cscript%3Ealert%28%22script%20injected%22%29%3C%2Fscript%3E%3Ca%20href=%22">User submitted scripts are possible.</a>`

In case markdown messes with the above code, see also the [soylentnews.org post revealing it here.](https://soylentnews.org/comments.pl?sid=8097&cid=200636#commentwrap).

**Comment by VortexCortex** [comment]
Though I haven't had time to test it yet, it occurs to me that in `_url_to_domain_tag_()`, just after [line 3755 of Slash::Utility::Data](https://github.com/SoylentNews/rehash/blob/c759ffc0f8b0bf1272289897e4b57e136fbc9f67/Slash/Utility/Data/Data.pm#L3755) `$info` should take a trip through `strip_title()` before it has a chance to become part of the title attribute or domain tag via `$href` or the returned string.

**Comment by paulej72** [comment]
decode script:
`<a href="https://vc/"><script>alert("script injected")</script><a href="">User submitted scripts are possible.</a>`

**Comment by TheMightyBuzzard** [comment]
Fixed, non-retroactively in #188

**Comment by paulej72** [comment]
addDomainTags uses URI to create a new abs uri based on what is in the href of the a tag.  This is used to find the hostname to put in to the title and [domain tag] part of the url.  URI decodes the host and when the url is specifically crafted as above the whole href string is used as the host and gets passed as the domain tag.  We now strip all html from the decoded url before it gets to addDomainTags.  See #191.
