### ISSUE TITLE
Kill the Launch News Slashbox

### ISSUE THREAD

**Issue by juggs** [SoylentNews/rehash#197]
As subject. The Launch News slashbox is past its sell by date, junk it.

Secondary, in Preferences, why is the Site News checkbox greyed out? It's checked but unconfigurable. Either make it configurable or drop it from the Prefs page, it's hardly a preference if we're going to make it "always display, like it or not".

With love.. juggs :)

**Comment by paulej72** [comment]
set to hidden in Block admin page. (was the features block)
