### ISSUE TITLE
UTF-8 Problem during story submission

### ISSUE THREAD

**Issue by janrinok** [SoylentNews/rehash#2]
During submission drafting, any Attempt to review a submission containing UTF-8 characters results in an 'Internal Server Error' page.

**Comment by NCommander** [comment]
Does this happen on production or just devtest?

**Comment by janrinok** [comment]
Only on devtest.  Production accepted the subs without problem.

**Comment by NCommander** [comment]
Did this get fixed?

**Comment by TheMightyBuzzard** [comment]
Yeah, I didn't remember it being an issue or I would have closed it when i fixed it.
