### ISSUE TITLE
Unicode and Comment Moderation message

### ISSUE THREAD

**Issue by tenno-seremel** [SoylentNews/rehash#200]
> Sexist video games, posted to Survey Says Even Teenage Boys are Sick of Sexist Video Games, has been moderated TouchÃ© (+1).
> It is currently scored TouchÃ© (3).

Something's broken about unicode this moderation message thing.

**Comment by Open4D** [comment]
Story titles are also affected.  A non-ASCII apostrophe in a story title displays correctly throughout the soylentnews.org website, _except_ when it appears on the [Your Messages page] (https://soylentnews.org/my/inbox)

Example; the word "Didn’t" (with a non-ASCII apostrophe) appears in the title of this story: https://soylentnews.org/article.pl?sid=15/09/20/032232

**Comment by TheMightyBuzzard** [comment]
Yeah, there are a few known unicode issues left. I'm out of state right now at the moment on a chincy little laptop but I'll try and track down the problem once I get home and have a proper keyboard and mouse.

**Comment by TheMightyBuzzard** [comment]
I think this one was fixed in the last site update.

**Comment by tenno-seremel** [comment]
This is indeed fixed now.
