### ISSUE TITLE
RFE: Change wording for nonaccepted story submission from 'rejected' to 'declined'

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#207]
Examples of this can be found in a user's info page; e.g.: load this page:
   https://soylentnews.org/~martyb/
and scroll down to:
   Recent Submissions

It appears that a story submission is either 'accepted' or 'rejected'.  Please change 'rejected' to 'declined'.

We recently posted a story:
   https://soylentnews.org/meta/article.pl?sid=15/08/06/0551219
entitled:
   Looking for Some More Editors (and Submissions)

And this was specifically mentioned in this comment:
  https://soylentnews.org/meta/comments.pl?sid=8839&cid=220703#commentwrap

Which lead to much discussion in the #editorial channel on IRC.  It was generally agreed that 'rejected' is a relatively harsh term whereas 'declined' sounds more polite and carries less connotation of rejection of the user's efforts, and hence of the user.

**Comment by TheMightyBuzzard** [comment]
Done in #216.
