### ISSUE TITLE
Story Submission Resource Shows Unavailable

### ISSUE THREAD

**Issue by cmn32480** [SoylentNews/rehash#208]
When creating a story submission (sub 1), if another user submits a story (sub 2) while sub 1 is being prepared, when sub 1 gets submitted, the error message "Resource No Longer Available" sometimes appears.

This does not happen every time, and I am trying to find the exact steps for reproduction.  I will update once I have them.

**Comment by cmn32480** [comment]
This seems to happen when the submission page is left open for too long.

**Comment by paulej72** [comment]
This is by design.  The resource system will time out old stuff so that some creeps can't open up a bunch of windows and try to spam the system all at once.
________________________________
