### ISSUE TITLE
automated checker to detect links as text and highlight to editor

### ISSUE THREAD

**Issue by crutchy-** [SoylentNews/rehash#212]
<Gravis> the anchor was in the text as well as actually being the anchor, effective <a href="https://soylentnews.org/article.pl?sid=14/06/07/0711244">https://soylentnews.org/article.pl?sid=14/06/07/0711244 ("How to Get Girls Into Coding")</a> - would be handy to have some way of highlighting automagically for editors

submitted by exec on behalf of crutchy from #Soylent @ irc.sylnt.us

**Comment by crutchy-** [comment]
suggestion was originally by Gravis

**Comment by TheMightyBuzzard** [comment]
Oh hell no. There's already enough ajaxy bullshit in the admin interface.
