### ISSUE TITLE
rss and atom not working

### ISSUE THREAD

**Issue by CommonJoe** [SoylentNews/rehash#213]
I use the rss function.  As of September 7, 12:43 PM, I have not downloaded anymore new stories, although I can see new stories have appeared on the website.  Looking at the atom and rss links on a web browser, it appears both are affected.

**Comment by paulej72** [comment]
Fixed

**Comment by CommonJoe** [comment]
Thank you!  :)

Common Joe

**Comment by TheMightyBuzzard** [comment]
Closing as this was caused by slashd crashing.
