### ISSUE TITLE
SUGGESTION: Mod-banned users require indicator

### ISSUE THREAD

**Issue by juggs** [SoylentNews/rehash#215]
Scenario
=======

Logged in user Mods a post as Spam. Subsequently, staff review comes along and chooses "UnSpam AND Ban" option. User is banned from Moderating on an escalating scale of ban length.

Currently
=======
The Mod-Banned user gets no indication they are Mod-Banned - other than the absence of Mod Points typically distributed each day.

Proposal - MUST
==============
Present Mod-Ban to user thus:
1. Logged in User receives in-site Message advising of Mod-Ban and Expiry date.
2. Logged in User has advisory message regarding Mod-Ban and Expiry date visible to them somewhere within their own account section.
3. Mod-Ban MUST NOT be visible to other users. We do not want to create exiles or pariahs.

Proposal - DESIRABLE
=============================
Visibility for the Mod Banned user as to why they are Mod Banned with link to causal Comment or Mod. Achieved in an anonymised way. ^^ well it says "DESIRABLE" :)

**Comment by TheMightyBuzzard** [comment]
Working on this.

**Comment by TheMightyBuzzard** [comment]
Done. Just replaced the moderation slashbox with info reflecting the ban in #218
