### ISSUE TITLE
subscription: formatting error in confirm of amount less than $10

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#233]
1.) Logged onto dev (https://dev.soylentnews.org/) as user martyb,
2.) Clicked on "Subscribe" in the Navigation slashbox (https://dev.soylentnews.org/subscribe.pl)
3.) Selected radio button "Buy Subscription for martyb"
4.) Selected radio button "30 day ... 5.00"
5.) Clicked "Continue" button.
6.) Saw page repaint with "Preferences: Confirm subscription and choose payment type" at top.
7.) Saw this message on that page:
You've decided to purchase:
    A 30 Day subscription for martyb (76) for $05. 
8.) Formatting is incorrect.  Expected to see:
You've decided to purchase:
    A 30 Day subscription for martyb (76) for $5.00
NOTE: the digit zero between the $ and the '5' in the current message.
NOTE: the lack of digits for cents in the current message.

**Comment by paulej72** [comment]
Fix in upcoming pull.
