### ISSUE TITLE
subscription: fails to note stripe is valid payment option on intro page

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#234]
1.) Launched dev: https://dev.soylentnews.org/
2.) Logged in as martyb
3.) Clicked on Subscribe (https://dev.soylentnews.org/subscribe.pl) in navigation slashbox
4.) Saw new page display with 'title' of: "Preferences: Configuring Subscription for martyb (76)"
5.) Scrolled down to the "Purchase Subscriptions" area.
6.) Saw this as the first paragraph:
You can buy a subscription for yourself or a gift subscription for another user. Payments are handled by PayPal (for PayPal payments and credit cards) and BitPay (for Bitcoin payments). The recipient of a gift subscription will be notified of your purchase through email. Information about subcriptions can be found in the Why Subscribe FAQ.
7.) Expected to see mention that one could pay by credit card using stripe.

**Comment by paulej72** [comment]
Fixed in #250
