### ISSUE TITLE
Automate [more after the break], shorten it to [more], make it clickable

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/rehash#237]
https://soylentnews.org/comments.pl?sid=11553&cid=287203

1. When loading the SoylentNews main page, stories with extended copy should have an automatically generated "[more after the break]" text in the summary.
2. The text should read "[more]" instead of "[more after the break]".
3. Clicking "[more]" should load the extended copy (the rest of the summary) using JavaScript.
4. "[more]" text could disappear if the extended copy is successfully loaded. Or the "[more]" text does not disappear but changes to "[less]". Reusing the "[more]" text would load the extended copy from memory instead of requesting it from the server again, if extended copy is loaded from the server in the first place instead of being hidden by default.

**Comment by paulej72** [comment]
See #275.
