### ISSUE TITLE
No link back to story on comment forms

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/rehash#256]
Google searches sometimes link directly to the comment form for some articles, such as:

https://soylentnews.org/comments.pl?sid=11977&op=reply&threshold=0&commentsort=0&mode=improvedthreaded

(search for site:soylentnews.org eagles drones)

There is no link to get back to the story. The <h3> containing the article headline should link back to the story.

**Comment by paulej72** [comment]
fixed in my next pull request.
