### ISSUE TITLE
Admin Statistics Graphs Are Broken

### ISSUE THREAD

**Issue by cmn32480** [SoylentNews/rehash#257]
Steps to recreate:
Click on INFO in the the admin interface.
Choose Any Report
Note that the Graph icons are broken.
Click on broken icon
Get Data, but no graph.

Assign it to Bytram.  This submission was his idea.

**Comment by paulej72** [comment]
the graphing perl module is broken and I was not able to fix it.  I can't remember the name of the module, but it is loaded from the Stat pm.

**Comment by paulej72** [comment]
make sure apt-get install libgd2-xpm-dev is run.
Installed from CPAN: Template::Plugin::GD and GD::Graph.  GD is no longer part of Template Toolkit by default and needs loaded separately.
