### ISSUE TITLE
stories with 100 comment

### ISSUE THREAD

**Issue by mechanicjay** [SoylentNews/rehash#258]
A story which has *exactly* 100 comments, will show 100 comments on page 1 and offer up a page 2 link, which displays 0 comments.  Def not critical, just a little goofy.

**Comment by TheMightyBuzzard** [comment]
Sounds like yer basic off-by-one bug. I'll give it a look tomorrow after I finish making moderating take you back to the furthest down comment you moderated.

**Comment by TheMightyBuzzard** [comment]
This'll be fixed in the new thread pulling and paginating code. Not going to fix the old version.
