### ISSUE TITLE
Feature Request: Diaspora/social integration with SoylentNews accounts

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/rehash#260]
Suggestion comes from [this comment and thread](https://soylentnews.org/comments.pl?sid=12060&cid=300531#commentwrap).

**Comment by TheMightyBuzzard** [comment]
mewe and friendica also suggested.

**Comment by TheMightyBuzzard** [comment]
closing due to overwhelming amounts of meh, moderate amounts of hell no, and small amounts of yay.
