### ISSUE TITLE
Italics in hyperlinks adds unnecessary spacing

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/rehash#265]
It's impossible to italicize text inside a hyperlink without the system adding additional spacing.

https://soylentnews.org/submit.pl?op=viewsub&subid=12209

See "DSCA official told Defense News".

Italicized text in hyperlinks is common because of the italicization of news outlet names or published works.

**Comment by TheMightyBuzzard** [comment]
It's not _that_ common or it would have reared its buggy head before now. Also, I'm not seeing any extra spacing. Mayhaps tis your font?

**Comment by soytakyon** [comment]
It's VT100. And this is pretty common for me, I just have never filed a bug report on it.

It's possible to do `<em><a href="">Text</a></em>` instead, but obviously not for links with only partial italics.

**Comment by TheMightyBuzzard** [comment]
Not font related. Or rather it is in that non-monospace fonts don't show the space that actually is there and shouldn't be. Unfortunately this one is going to be a bitch to find.

**Comment by marty-b** [comment]
Agreed that it is not font-related.  The problem arises when the code detects adjacent elements and inserts a space where none previously existed.
Here is another example:

`THIS<sup><em>test</em></sup>THAT<br>`
`THIS<em>test</em>THAT<br>`
`THIS<sup>test</sup>THAT<br>`

Notice when viewed on the site how a space is inserted between the SUP and EM tags. I expect there are plenty more examples.

**Comment by marty-b** [comment]
TMB wrote: "It's not that common or it would have reared its buggy head before now."
It reared its head a LONG time ago and has slowly driving me crazy. I understand that it probably arises in the balance_tags code, which I hear is a real bear to work on, so I've been reluctant to mention it.  But, it has become increasingly annoying and seeing that another person also finds it so, I must pipe up and suggest it needs fixing.

**Comment by TheMightyBuzzard** [comment]
Fixed poorly in #303

**Comment by marty-b** [comment]
Here is another instance that I have observed when editing a story using:
`https://soylentnews.org/admin.pl`
Here is a specific example. Launch:
`https://soylentnews.org/admin.pl?op=edit&sid=16/09/28/1229204`
There are two places where one cannot remove the space between the `<p>` and the `<a ...>`
1) `<p class="byline"> <a href="//soylentnews.org/~takyon/">takyon</a>`
2) `<p> <a href="http://www.bbc.com/news/world-europe-37495067">Another investigation has pointed towards Russia</a>`
A) Deleted the space, clicked "preview", and saw the space reinserted.
B) Deleted the space, clicked 'update', viewed the story at: `https://soylentnews.org/article.pl?sid=16/09/28/1229204`, viewed source, saw space reinserted.

**Comment by marty-b** [comment]
<p>I missed seeing this before, sorry.  Above, Soytakyon noted:

&nbsp; &nbsp; It's possible to do `<em><a href="">Text</a></em>` instead, but obviously not for links with only partial italics.

That has a problem, however, when someone has requested (in their preferences) the display of a domain name following a link. It then displays the bracketed domain name in italics, too.  So, in that case, this:
 &nbsp; &nbsp; `<em><a href="https://example.com/path/index.html">index.html</a></em>`
would be rendered:
 &nbsp; &nbsp; _index.html [example.com]_

**Comment by TheMightyBuzzard** [comment]
Easy enough fix, if just as hacky. I'll add it in to this pull request tomorrow.

**Comment by paulej72** [comment]
fixed in #314.
