### ISSUE TITLE
meta stories and the hold queue

### ISSUE THREAD

**Issue by TheMightyBuzzard** [SoylentNews/rehash#266]
Slap a meta sub in the hold queue and it disappears into the ether even though it shows up in the counts and can be accessed if you still have a link directly to the sub handy.

**Comment by soytakyon** [comment]
Is this related to issues where browsing the /breakingnews/ or /meta/ lists only show you stories with that nexus?

https://soylentnews.org/meta/admin.pl
https://soylentnews.org/breakingnews/admin.pl

**Comment by TheMightyBuzzard** [comment]
Probably in the same area of code but what you're describing is expected and desired behavior because we eventually want to be able to have separate editors for separate nexuses who can only see/monkey with their own stuff. Not showing up at all if it's in the hold queue and a nexus isn't.

**Comment by TheMightyBuzzard** [comment]
Closed as I can't reproduce it now.
