### ISSUE TITLE
collapsible comment trees with only css

### ISSUE THREAD

**Issue by TheMightyBuzzard** [SoylentNews/rehash#267]
See here for an example: http://www.thecssninja.com/demo/css_tree/

**Comment by paulej72** [comment]
I think I have seen this before.  We need to see what browsers this does not work on, but it may be what we need.

**Comment by paulej72** [comment]
that is some fucked up shit.  not sure how easy it would be to do this.

**Comment by TheMightyBuzzard** [comment]
I'm guessing not that hard once we wrap our heads around it. How hard can css be compared to perl that other people wrote?

**Comment by paulej72** [comment]
See #270.
