### ISSUE TITLE
Qualification for display in "Most Recent Journal Entries" rehashbox

### ISSUE THREAD

**Issue by juggs** [SoylentNews/rehash#279]
PROBLEM:
Accounts signing up then posting commercial spam Journal entries in order to appear on most user's view of the main SN site, within the Most Recent Journal Entries box. Whilst offering zero other contribution to the community.

SOLUTION:
A. Most Recent Journal Entries only to be populated with Journal entries by accounts with a Karma > N. 5 to be the initial value for N (that would hide all currently seen Journal spam from view), but should be an easily tweaked parameter should we need to revisit this threshold).

B. Addition of a link to "Unfiltered Most Recent Journal Entries" to be added to the bottom of the Most Recent Journal Entries rehashbox so users can easily compare the filtered to unfiltered lists.

ADDENDUM:
This change will need to be clearly announced and rationale explained. We will also need to monitor effectiveness in case spam accounts begin to farm Karma in order to route around this change.

**Comment by paulej72** [comment]
if we set that level via var, we can change it if needed later.

**Comment by TheMightyBuzzard** [comment]
Solved in #414. Defaults to not showing journals by anyone with a karma under 10. Tunable by journal_sb_min_karma in vars.
