### ISSUE TITLE
Increase size of submission deletion reason

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/rehash#286]
Maybe give it size="75" like the title/dept input boxes. Or at least size="50"

**Comment by marty-b** [comment]
The current field for entering the reason for deletion is coded as a simple INPUT of type TEXT, e.g.:
`   <input type="text" `name="rejectreason">`

whereas "Editors Notes", "Intro Copy", and "Extended Copy" are each coded as a TEXTAREA, e.g.:
`   <textarea rows="3" cols="60" name="notes" maxlength="1023" wrap="virtual" class="fullbox" id="itsalltext_generated_id_notes_2"></textarea>`

This may be browser-related (I use Pale Moon 26.2.1 x86 on Win 7 Pro x64), but I see misspellings highlighted (with red squiggles under the misspellings) in TEXTAREAs which I DO NOT see highlighted for a TEXT INPUT.

So, please consider changing the Delete Reason to be a TEXTAREA while you are at it.  Possibly with the same dimensions as in the above TEXTAREA snippet.

NOTE: I am not sure about the limits on length of rejectreason field or how the page should be laid out.

**Comment by soytakyon** [comment]
The title and dept boxes are <input type="text"> and they are longer due to the attribute size="75". So it is not necessarily necessary to change the necessary element to TEXTAREA.

https://developer.mozilla.org/en-US/docs/Web/HTML/Controlling_spell_checking_in_HTML_forms

What's more, this indicates that spellcheck="true" can enable spellchecking on input type="text".

Unfortunately, <input type="text"> seems to not allow dragging the corner to increase the height/width.

At the very least, changing the delete reason box to <input type="text" size="50" spellcheck="true"> would probably be a quick temporary fix for this.

Finally, this issue can be merged with #283. Sorry about that.

**Comment by paulej72** [comment]
Fixed in #329
