### ISSUE TITLE
User pages with a lot of stuff are too slow

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/rehash#288]
http://soylentnews.org/~takyon/

For the sake of my vanity, and as a reminder of the problem, this issue was created.

**Comment by soytakyon** [comment]
Opening my page is still a reliable way to create a 503 error.

**Comment by paulej72** [comment]
It is hitting the varnish timeout I believe.  We could change change that an it would just take a bit longer to load.

OK changed /etc/varnish/soylentnews.vlc:

    .first_byte_timeout = 20s; #was 5s
    .between_bytes_timeout = 40s; #was 20s (this was the fix)

Should be OK for  a while now, but we need to paginate the subs table or only show the last x mounts.

**Comment by TheMightyBuzzard** [comment]
This got fixed in 17_05 I believe. Closing until it again becomes a problem.
