### ISSUE TITLE
Placement of "Replies below your threshold"  

### ISSUE THREAD

**Issue by frojack** [SoylentNews/rehash#290]
I read SN with the following Display Mode settings:  
Situation:
Display mode: Threaded  (Same problem with improved threaded)
Sort order :  Oldest first
Threshold: 1
Breakthrough: 0
Reparent: checked 

 Problem:

With this setting, "N Repels below threshold" are bundled at the end of the displayed comments (at any given level). 

The reparented replies appear to be replies to the the starter post, but are actually replies to low ranked posts which are at least 1, and often 2 or 3 levels deeper.  The indentation is also wrong, with the reparented sitting at an indent level suggesting they are a reply to the level-starter.

**This perverts the reading of the thread**.  Often quite badly, and often causing further replies that occur only because it was not clear that the reparented post was on a separate subthread. 

It seems to me that Reparenting is some kind of kludge that SN inherited from Slashcode.

Some possible fixes...: (might be used in combinations)

1) Fix the indenting.  Its wrong, and the reparented posts should be properly indented to the level they would actually appear.  There are other indentation bugs as well. See bottom.

2) If there is a reply which is filtered, and that reply has a child reply,  then:

2.a) Place a line "1 Reply beneath your threshold"  where it actually occurred in the thread, rather than at the end of the replies that do appear.  (Even if that means several additional instances of this line in the conversation.)   

2.b) In this case, the reparented lines would not need "reparenting" per-se,  and would appear right after the properly placed "1 Reply beneath your threshold.  You could rename that option to Reveal or Not Reveal replies to filtered posts - instead of reparent them.

3) If there is a reply which is filtered, and that reply has NO child reply, do as is done now, and insert 
"N Replies beneath your threshold" at the end of this level, or put it where it belongs.  It doesn't matter in this case. ativly

4) If a reply was filtered, but had a highly rated reply (higher than "1", then almost by definition the filtered reply was at least a 1 (interesting), simply because someone replied, and that reply garnered an up-mod.  (I will often up-mod and AC that I reply to simply because the mere fact that I replied means it was interesting (positively or negatively) to me.

4a) Arbitrarily raise filtered posts to the threshold if there was a reply that was Above the threshold. 
4b) Show a snippit of the filtered post in light grey font just below the "1 Reply beneath" line

Note:  I realize that in complex threads, the worthwhile "revealed" post might be preceded by  a sequence of nested "1 Reply beneath your threshold" lines simply to carry the indentation to the proper level.  This would be clearer than what we have now. 

 Note:  I used this thread as an example in writing this:
https://soylentnews.org/comments.pl?sid=14422&cid=372614#commentwrap
And you will note that indentation is IMMEDIATELY broken at the first reply.

**Comment by TheMightyBuzzard** [comment]
Soon to be irrelevant but thankey for the exceptionally detailed writeup.

**Comment by TheMightyBuzzard** [comment]
Should be solved in #273. I'll reopen if not.
