### ISSUE TITLE
Accessing submissions that have been 'Held'

### ISSUE THREAD

**Issue by janrinok** [SoylentNews/rehash#3]
On the submissions page, there is the option to 'Back, Hold or Quik' submissions.  Having stories just sitting on the subs list deters users from submitting new entries and it would be useful to be able to 'Hold' stories that might be best released at a future date.  Currently, when a submission is 'Held', it is removed visually from the submissions list but no-one seems to know where it is moved to, nor how to access a story that has been held and is now invisible.  A simple way of accessing and managing these stories would be useful to editors.  I have no idea what the 'Back' selection does but the same requirement might be necessary. It appears to behave in a similar fashion to the 'Hold' option.

**Comment by mrcoolbp** [comment]
Reading through some of the docs, these features (back, quick, hold) are just methods of "classifying" for editors. However, testing on dev, assigning any of these "classifications" to a submission does in fact make it "dissappear" from the submissions list.

HOWEVER, selecting one of these "classifications" from the drop-down just right of "Classification" at the top of the (submission list) page, and clicking the "Filter Submissions" button on the right, will display (only) these stories. In that drop-down, it shows how many stories are in each classification. Of course I'd like to see these simply appear in a "seperate" list below the other stories (similar to how "merged" stories appear below the list with an <hr> seperator), I'd say this feature is working as inteded.

**Comment by mrcoolbp** [comment]
I suggest closing this for now
