### ISSUE TITLE
Links need fixed for nuxus support.

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#34]
Some links that should use gSkin.rootdir use constants.real_rootdir instead.  And probably vice verse.

**Comment by NCommander** [comment]
I haven't got a clue which should be which :(

**Comment by paulej72** [comment]
Think I broke the rss feed links.  need to redo.

**Comment by paulej72** [comment]
rss links fixed in #101

**Comment by BigBoneDaddy** [comment]
What be nuxus?

**Comment by TheMightyBuzzard** [comment]
Haven't heard of any more links not being nexus-friendly in a long time. Closing.
