### ISSUE TITLE
Search is not as useful because of sort order

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#36]
Since we no longer have scores, we need to be able to sort default by date descending with ascending as option.

**Comment by paulej72** [comment]
sphinx seems to be ignoring SetSortMode. Also sphinx.conf is not set up with correct mysql user and password.  Can't figure out if sphinx supports .my.cnf so that password is not in the sphinx.conf file.

**Comment by NCommander** [comment]
This was an utter PITA to fix; in addition, varnish needs a fix to exclude search.pl
