### ISSUE TITLE
Site doesnt display properly in Firefox or Chrome for windows

### ISSUE THREAD

**Issue by quantumflux1** [SoylentNews/rehash#366]
A ton of the following errors appear when loading the page in anything other than IE, for most content including CSS and images:

Content Security Policy: The page’s settings blocked the loading of a resource at self
Content Security Policy: The page’s settings blocked the loading of a resource at https://soylentnews.org/images/atomicon.gif (“img-src https://www.soylentnews.org https://www.paypalobjects.com https://q.stripe.com”).

**Comment by TheMightyBuzzard** [comment]
Yeah, that'd be because you're hitting the site either from our onion site or from www instead of the base domain. I'll see if I can get a workaround out for it sometime today.

**Comment by TheMightyBuzzard** [comment]
Fixed this a while back, just didn't close the Issue.
