### ISSUE TITLE
Feature Request: set the story queue to not display for 4/1 tomfoolery

### ISSUE THREAD

**Issue by cmn32480** [SoylentNews/rehash#377]
Please set the site story queue to not display from 3/31 00:01 through 4/1 23:59.  This will allow the editors to set up our annual tomfoolery and not have to get a dev to change it, and change it back (which we always forget to do).

We have a year to get this done.  Your eventual assistance is greatly appreciated.

-cmn32480

**Comment by Xyem** [comment]
Just to double check, you want it hidden for 2 days based on local time (of the server)?

**Comment by TheMightyBuzzard** [comment]
Yep. Assume UTC server time.
