### ISSUE TITLE
Bad links in "Most Recent Journal Entries" Slashbox for usernames containing +

### ISSUE THREAD

**Issue by bensonmitchell** [SoylentNews/rehash#380]
Right now there's a journal entry by user "a-zA-Z0-9$_.+!*'(),-"; the link in the "Most Recent Journal Entries" Slashbox is broken.

The link in the Slashbox, which doesn't work:
https://soylentnews.org/~a-zA-Z0-9$_.+!*'(),-/journal/

The correct link (from https://soylentnews.org/journal.pl?op=top):
https://soylentnews.org/~a-zA-Z0-9%24_.%2B!*'()%2C-/journal/

Note that three characters ('$', '+', and ',') are represented with % escapes -- however, only + appears to matter, as this link also works:
https://soylentnews.org/~a-zA-Z0-9$_.%2B!*'(),-/journal/

**Comment by TheMightyBuzzard** [comment]
Cheers. Yeah rehash currently treats "+" as " " as far as ~username links go; or maybe it's apache that does. We'll probably need to put a line in to always escape +s in usernames.

**Comment by TheMightyBuzzard** [comment]
I think we fixed this one in the 17_05 update but forgot to close it. Doing so now barring info to the contrary.
