### ISSUE TITLE
Initial db dumps need to be fixed.

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/rehash#4]
Topics are out of date and do not have icons.  Need to match with current topics and available icons.
Subscribe has double entry for karma bonus.

Probably other that will be collected here.

**Comment by NCommander** [comment]
Configuration files written out are not for Apache2. Partial fix already in progress on that.

**Comment by paulej72** [comment]
authors_unlimited should be set to 1000000 not 100.

**Comment by paulej72** [comment]
ALTER TABLE users_info ADD COLUMN points smallint(5) NOT NULL DEFAULT 0 AFTER bio;
ALTER TABLE users_comments DROP points;

Needs to be added to schema files

**Comment by paulej72** [comment]
rdfencoding = UTF-8  in vars  
should make site utf8 by default
