### ISSUE TITLE
Comments with no apparent subject using a unicode space

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/rehash#402]
Chromas used a unicode space or zero-width space character to make a comment with no apparent subject. When you get a Message about receiving the comment, the CID is not clickable like it normally would be.

https://soylentnews.org/comments.pl?noupdate=1&sid=21276&page=1&cid=559159#commentwrap

**Comment by TheMightyBuzzard** [comment]
Note to self: Make sure and kick chromas in his balls before fixing this one.
