### ISSUE TITLE
Change "Enemy" to "Foe"

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/rehash#406]
The frowny face in "Foe of Friend" comments has the title text "Enemy of Friend", which is inaccurate.

**Comment by TheMightyBuzzard** [comment]
Fixed. #407

**Comment by soytakyon** [comment]
This is still happening: http://puu.sh/ymU9j/f6eb1ab4ec.png

**Comment by TheMightyBuzzard** [comment]
Yeah, won't be pushing anything live until we have enough done to warrant doing so.
