### ISSUE TITLE
Spoiler tag doesn't work on Journal comments.pl

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/rehash#410]
See:

https://soylentnews.org/comments.pl?sid=22596
vs.
https://soylentnews.org/~takyon/journal/2762

It seems to work fine for articles:

https://soylentnews.org/comments.pl?sid=22588
https://soylentnews.org/article.pl?sid=17/11/16/013234

**Comment by TheMightyBuzzard** [comment]
Should be fixed above but currently still broken on prod.

**Comment by TheMightyBuzzard** [comment]
yep, fixed on dev and long since merged into master
