### ISSUE TITLE
Bad link for submitting rehash bugs provided on dev.soylentnews.org

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#42]
(1) Launched https://dev.soylentnews.org
(2) Scrolled down the page to where Quick Links slashbox appeared on the right-hand side; box contained: (Note, cannot seem to paste in raw HTML here; please bear with this representation)
   Quick Links
  Found a bug? Report it on the development tracker:
   &lt;a href="https://dev.dev.soylentnews.org/projects/soylentnews/"&gt; SoylentNews Dev &lt;/a&gt;
(3) Link should point to: https://github.com/SoylentNews/rehash/issues/new

**Comment by NCommander** [comment]
Fixed.
