### ISSUE TITLE
Noticeable Delay in Messages

### ISSUE THREAD

**Issue by gaddox** [SoylentNews/rehash#436]
I don't think anyone but a SN junky would notice, but there's a noticeable <15s delay between when a message-flagged event happens (comment reply, relationship status changed, etc.), and when you receive a message. I find myself seeing the replies, only from revisiting the stories or under my comments stats page, and then some time later getting a new message telling me I got a reply. 

Low-priority, just something I wanted to mention.

**Comment by TheMightyBuzzard** [comment]
That's actually the system working as designed. Message delivery is done by a slashd (basically custom cron) job at periodic intervals. Sometime in the distant past, /. decided it would be more efficient to deliver a whole bunch of messages every few minutes than to fire up the delivery system every time a worthy event occurred. And they were correct, though I don't know that we actually need that specific efficiency on SN

**Comment by gaddox** [comment]
Power users need the speed so their trades don't get slippaged' to hell. 15 seconds makes all the difference when you're going 50 lots deep into karma futures.
