### ISSUE TITLE
Comment not displaying

### ISSUE THREAD

**Issue by brad-richards** [SoylentNews/rehash#444]
Article "London Mayor Cracking Down on the Carrying of Knives". I have a comment #664298, currently showing in my profile modded as +4 Insightful. If I click on the comment link directly, I see the comment.

However, if I go to the article, this comment is not displayed. Not even if I set the threshold down to -1. The comment I was replying to is also gone (it had "public spaces" in the text; I don't remember who made it).

Or is there some mundane explanation that I am missing?
![soylent_comment_664298](https://user-images.githubusercontent.com/5278095/38514513-b4eae208-3c31-11e8-8a67-8c5f54ecf444.png)

**Comment by TheMightyBuzzard** [comment]
It's on page two. Took me a minute to notice as well.
