### ISSUE TITLE
SSL certs expired

### ISSUE THREAD

**Issue by dianevm** [SoylentNews/rehash#452]
Maybe for *.sylnt.us  https://logs.sylnt.us
https://certbot.eff.org/lets-encrypt/centos6-apache.html

logs.sylnt.us uses an invalid security certificate.

The certificate expired on June 29, 2018, 4:08:12 AM GMT-6. The current time is June 29, 2018, 6:07 AM.

Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by mrpg64** [comment]
Fixed, thank you.
https://soylentnews.org/meta/article.pl?sid=18/07/02/122218

**Comment by TheMightyBuzzard** [comment]
Yeah, I meant to close this yesterday when I finished up but I got distracted.
