### ISSUE TITLE
"Most Recent Journal Entries" not getting updated

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#46]
1.) Launched https://dev.soylentnews.org/
2.) Logged in
3.) In the left-hand side slashbox, clicked on Navigation > You > Preferences which took me to: https://dev.soylentnews.org/my/info
4.) Clicked on "Homepage" tab
5.) Under "Customize Slashboxes" (we might want to rename that), ensured that "Most Recent Journal Entries" (MRJE) was checked.
6.) Submitted a journal entry
7.) Looked in slashbox "Most Recent Journal Entries" on the right hand side.
8.) Did not see my Journal Article posted.
9.) Most recent Article I see there was: https://dev.soylentnews.org/~martyb/journal/254
10.) Noted that THAT Article was posted on "Thursday March 12, 2015"
11.) I have two Journal Articles that are newer than that which do not appear in the MRJE box:
a.) https://dev.soylentnews.org/~martyb/journal/257 which was posted on March 29 @ 5:39 PM UTC
b.) https://dev.soylentnews.org/~martyb/journal/258 which was posted on May 16 @ 12:02 AM UTC
12.) Critical Bug

**Comment by paulej72** [comment]
slashd was not running

**Comment by paulej72** [comment]
Actually portald was not running because sbindir was set wrong and SSL errors.  Fixed in #56
