### ISSUE TITLE
Sections order reshuffles and other oddities

### ISSUE THREAD

**Issue by NCommander** [SoylentNews/rehash#47]
I've noticed whenever we refresh the page on dev, when logged in, the order of sections changes randomly on page load. Furthermore, on Search and on user pages, only Breaking News shows up, not Meta, which I can't figure out ...

**Comment by paulej72** [comment]
Template fixed in pull #59 and the issues with meta fixed with changes in meta topic (set it to searchable).  Also removed the Series flag on Nexus as well.
