### ISSUE TITLE
No longer receiving e-mailed stories

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#48]
1.) Logged in as user 'martyb'
2.) Clicked on 'Preferences' link in the 'Navigation' slashbox.
3.) Found myself at: https://dev.soylentnews.org/messages.pl
4.) Clicked on the 'Messages' tab.
5.) Now at: https://dev.soylentnews.org/messages.pl
6.) In the 'Message Preferences' area, confirmed these selections: (unchanged for a long while)
a.) Daily Newsletter: E-mail
b.) Email Story: E-mail
7.) Last story e-mail that I received was: "[Dev.SN] Stories for 2015-05-09"
8.) Partial headers:
Date: Sat, 09 May 2015 02:00:03 +0000
From: noreply@dev.soylentnews.org
Subject: [Dev.SN] Stories for 2015-05-09
To: REDACTED
Precedence: list
Content-transfer-encoding: 8bit
Content-type: text/plain; charset="UTF-8"
Message-Id: <1431136803.536278-27292-slash-lithium@dev.soylentnews.org>
X-Bulkmail: 2.051
Content-Length: 11842

Dev.SN Daily Newsletter

**Comment by paulej72** [comment]
slashd was not running
