### ISSUE TITLE
.onion available header

### ISSUE THREAD

**Issue by Runaway1956** [SoylentNews/rehash#489]
An anonymous coward asked wny ".onion available" fails to show in the address bar on Soylentnews.  He had to explain, before I understood what he meant.  I refer you to the tor webside for an accurate explantion - https://support.torproject.org/onionservices/onion-location/

In short, a Tor enabled site should have an indicator in the address bar to inform a WWW user that the tor service exists.   The how-to can be found here - https://community.torproject.org/onion-services/advanced/onion-location/

Having been alerted to this issue by anonymous coward, I tested in two Chrome browsers, and in two Firefox browsers.  I can verify that ".onion available" does not appear in any of my address bars.

**Comment by TheMightyBuzzard** [comment]
And it won't unless someone who actually uses ToR wants to do the work. Right now we've essentially got me, myself, and I as far as coding goes and installing/configuring ToR so that I can support something that makes my other job as an admin more difficult is not on my to-do list at all.

**Comment by ennwise** [comment]
This has been accepted and added.
