### ISSUE TITLE
dev story comment counts not getting updated on main page

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#49]
1.) Launched https://dev.soylentnews.org
2.) Submitted story and posted it to the main page: https://dev.soylentnews.org/article.pl?sid=15/05/22/156217
3.) Submitted comments to the story.
4.) Refreshed the main page
5.) Comment count shown for the story is "0", but when I open the story, I see there are (atm) 7 comments.  More than 90 minutes has elapsed since the story and the first comment to it were posted.
6.) SEE ALSO: https://dev.soylentnews.org/article.pl?sid=15/05/17/1323253 which was posted 5 days ago.  Main page shows "0" (zero) comments.  When I open the story, I see 4 comments there.

**Comment by paulej72** [comment]
slashd was not running.
