### ISSUE TITLE
Mod points not being issued

### ISSUE THREAD

**Issue by NCommander** [SoylentNews/rehash#494]
Ongoing issue since the downsizing of infrastrucutre, please put all notes here.

**Comment by cosurgi** [comment]
I am not getting modpoints: cosurgi (272)

**Comment by Runaway1956** [comment]
The slashbox for "most recent journal entries" is not working.

**Comment by Fnord666b** [comment]
I'm not getting mod points either - userid fnord666

**Comment by NCommander** [comment]
I'm tinkering this on production because there's no obvious problems in the log. There was one semi broken query which I tried patching, so please let me know if the issue is resolved since it won't affect all users if I'm right.

**Comment by cosurgi** [comment]
I have the modpoints!

**Comment by Fnord666b** [comment]
I have mod points now and they are decrementing when used. Thank you!

**Comment by Runaway1956** [comment]
Last evening, I found that I had the ability to moderate posts - but still didn't see the slashbox informing me that I had mod points.  I did a couple moderations, then looked for the slashbox, and there it was.  So, mod points are working now, but it did some kind of hiccup in the process of "activating".  Maybe that info is useful.

**Comment by NCommander** [comment]
my general sense is something that generates the slashboxes is broken; quite possibly portald, but the spagetti is deep here.
