### ISSUE TITLE
Sig silently truncates to 120 chars

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#50]
1.) Launched dev: https://dev.soylentnews.org/
2.) Clicked on my Preferences link: https://dev.soylentnews.org/my/info
3.) Entered this text in the 'Sig' text entry area:
Mauris in tortor ac metus suscipit adipiscing non eget mauris. Sed velit mauris, consectetur in lobortis sed, commodo net
4.) Clicked preview button
5.) Saw text truncated; the "t" of "net" was truncated, but no message or warning of any kind was displayed.

**Comment by paulej72** [comment]
This was well known on /., but the textbox should be set to only allow 120 max.

**Comment by paulej72** [comment]
sig is stored as varchar(200), but buffer is to allow domaintags.  The textbox does say there is a 120 char limit.

**Comment by paulej72** [comment]
Fixed in #57
