### ISSUE TITLE
Bio user field allows more than 255 chars.

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#51]
1.) Launched dev: https://dev.soylentnews.org/
2.) Clicked on 'Preferences' link: https://dev.soylentnews.org/my/info
3.) The "Bio" text entry area has a note blow it which states:
   This information is publicly displayed on your user page. 255 chars. 
4.) Pasted in text from "lorem.txt";
    wc lorem.txt
     43    2197   14897 lorem.txt
5.) Clicked on 'Save User' button.
6.) Selected all text in the Bio text entry area, pasted into a file, ran through wc (word count); saw:
     wc  zxzx.txt
      3     153    1026 zxzx.txt
7.) Examined the file and noted the last two chars were 0x0d 0x0a (CRLF); so actual saved Bio text was 1024 chars long.
8.) Problems:
a.) The stated size of the Bio field was 255 chars; more than that was saved.
b.) I had entered 14897 chars; it was truncated to 1024 chars without any error message or warning.

**Comment by marty-b** [comment]
This is the entire lorem.txt file I used:
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porta tempus nunc, vel gravida eros. Fusce ac sapien sed elit adipiscing pharetra at vel neque. Cras consequat a nisi vitae interdum. Nulla pulvinar, nisi a varius venenatis, lorem mauris posuere nulla, sit amet venenatis enim mauris quis tellus. Fusce nec ullamcorper lorem. Proin vulputate leo sapien, sollicitudin tincidunt urna eleifend vel. Etiam eleifend nulla id leo egestas interdum. Sed dignissim mauris eget tincidunt fermentum. Sed nec felis et nisl ullamcorper gravida varius in augue. Morbi ac erat quis dolor ultricies pulvinar. Vivamus sagittis viverra leo et sollicitudin. Maecenas at vulputate tortor. Donec ipsum erat, bibendum vel viverra eu, ornare vel sem.

Mauris in tortor ac metus suscipit adipiscing non eget mauris. Sed velit mauris, consectetur in lobortis sed, commodo nec turpis. Quisque placerat, mauris vel sollicitudin placerat, libero lacus accumsan mauris, a fermentum est ligula nec nisl. Aenean mi odio, vulputate vel augue nec, suscipit eleifend magna. Praesent venenatis urna id enim dapibus, vel pulvinar felis sagittis. Aliquam vulputate pulvinar arcu id tincidunt. Vestibulum malesuada aliquam auctor. Suspendisse non elementum ligula. Cras lacinia a arcu tempus aliquet. Ut ullamcorper luctus diam in sodales.

Nulla ultricies volutpat nisl blandit iaculis. In tempor id velit ullamcorper dignissim. Quisque sit amet laoreet risus. Integer a laoreet magna. Integer congue sem vitae diam molestie commodo. In auctor metus luctus consequat mollis. Pellentesque a mattis quam. Nulla facilisi. Duis et lacus sit amet magna volutpat laoreet eget non lectus. Duis nec elit egestas, faucibus ante vitae, dictum neque. Mauris porttitor urna eget rhoncus congue. Fusce rutrum imperdiet tellus.

Pellentesque lacinia nulla id metus pharetra viverra. Nulla sed leo velit. Pellentesque enim leo, fringilla at ipsum in, porta sagittis lectus. Ut quis leo facilisis, placerat ligula at, vestibulum nibh. Pellentesque venenatis dui at leo tempus convallis. Pellentesque bibendum imperdiet purus vel accumsan. Ut nisi purus, consequat in pellentesque rhoncus, sollicitudin at tortor. Vivamus sollicitudin porttitor augue a euismod. Suspendisse eleifend turpis sed felis venenatis, eget aliquet mi varius. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi rutrum ac felis eu ullamcorper. Nullam nec massa luctus diam laoreet ultrices. Donec mi ligula, ornare at mi vitae, tincidunt consequat nunc. Morbi consectetur pellentesque arcu eget fringilla. Proin quis nibh justo. Aenean sodales nisl arcu, a adipiscing nisi ultrices at.

Mauris tristique, augue sit amet vulputate adipiscing, tellus mauris convallis augue, non suscipit quam magna quis sem. Nam volutpat in mauris eu cursus. Suspendisse vitae dignissim ipsum. Praesent erat leo, aliquet nec arcu vel, pharetra rhoncus sapien. Maecenas quis purus odio. Proin dictum commodo sapien a egestas. Aenean luctus commodo nisi sed fermentum. Phasellus euismod fringilla sapien, quis aliquam tellus commodo eget. Morbi vitae magna dapibus, feugiat risus quis, pharetra turpis. Maecenas imperdiet, elit vitae scelerisque fringilla, justo massa laoreet augue, sit amet tempor ligula sapien in nulla. Vestibulum vitae dui lacus. Ut a suscipit tellus. Ut tincidunt condimentum diam, et faucibus tortor porta quis. Aliquam vel est tortor. Pellentesque auctor, turpis at sagittis egestas, erat sapien pharetra arcu, et rutrum ipsum mauris id est.

Vivamus ultrices venenatis tempor. Vivamus at aliquet libero, in dignissim est. Aenean libero lectus, fringilla ac lectus vel, feugiat pellentesque ligula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis adipiscing lacus quis magna mollis feugiat. Praesent augue est, commodo eget orci pharetra, ornare dapibus nisi. Nullam condimentum neque eu lorem vehicula, nec dapibus lorem congue. Quisque blandit dolor nec hendrerit aliquet. Nunc in magna arcu. Vivamus sed iaculis diam, sit amet cursus diam. Nullam metus lorem, molestie sed gravida rutrum, ornare at arcu. Nullam id purus at felis elementum ultricies in id erat. Nunc nec ipsum felis.

Ut ac quam sit amet mauris mattis blandit. Vestibulum suscipit magna eu purus sollicitudin pharetra. Cras volutpat augue non diam elementum, et cursus dui vehicula. Nam pharetra interdum lorem eu ullamcorper. Nunc ut nibh urna. Nulla vitae rutrum odio, a eleifend dui. Vivamus quis justo ullamcorper, iaculis sapien eu, scelerisque nunc. Maecenas vitae vehicula nulla. Aenean tempor elit cursus leo gravida dictum. Aliquam erat volutpat. Nam et nisi tellus. Phasellus feugiat a turpis vel vulputate.

Nullam libero risus, ultrices sit amet malesuada tristique, feugiat in tortor. Nulla non augue non eros placerat rutrum. Ut adipiscing bibendum lorem vel facilisis. Suspendisse porttitor purus ut nisl consectetur, vitae laoreet urna viverra. Mauris libero mauris, dictum eu magna eu, condimentum posuere lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque nibh mauris, aliquet ac posuere sed, interdum in metus. In aliquam suscipit orci sit amet euismod. Duis quis dolor id leo fringilla ornare. Cras ac massa est. Duis sit amet velit vitae diam tristique imperdiet nec at elit.

Aenean quam eros, tempus sagittis orci et, mattis euismod erat. Nulla euismod, ipsum sit amet hendrerit viverra, purus arcu egestas arcu, sit amet porttitor lorem turpis nec risus. Pellentesque vitae sem non augue sollicitudin gravida. Integer aliquam, magna nec dictum consequat, ipsum justo ultrices mi, ut luctus diam leo et tortor. Vivamus interdum volutpat felis, non tristique mi ornare ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at sem id sapien porttitor porttitor et quis massa. Praesent turpis nisl, pulvinar non rhoncus vel, molestie quis turpis. Cras consectetur ipsum quam, vel scelerisque sem facilisis sit amet. Vestibulum ultrices pharetra eros, in placerat massa imperdiet eu. Ut placerat elementum eros eu porta. Vivamus quam odio, vulputate egestas sodales vitae, tempor ac eros. Vestibulum ipsum odio, tincidunt vitae laoreet at, pharetra in ipsum. Suspendisse massa nulla, blandit in ligula sit amet, mattis tristique felis.

Sed at eleifend erat. Sed sit amet vulputate nisl. In sed augue quis sapien cursus tincidunt eget et nunc. Cras eget erat sed mi blandit feugiat. Nam nec accumsan felis. Donec rutrum ipsum at risus pulvinar, nec convallis dolor pellentesque. Duis nec est ac risus auctor congue condimentum et est. Sed sit amet aliquet dui. Proin tempor diam sed varius commodo. Integer vitae arcu vel magna cursus convallis.

Morbi non gravida quam, in lacinia felis. Curabitur eget semper arcu, eu sagittis magna. Nullam sed enim in sem lobortis adipiscing. Aenean vel viverra nunc. Cras vel nulla a ligula vulputate condimentum ut dictum orci. Nunc lacus massa, mattis non augue in, viverra dignissim sapien. Praesent euismod justo felis, quis porttitor neque tincidunt et. Aliquam justo lectus, imperdiet vel imperdiet dapibus, vulputate sit amet mauris. Curabitur sed nunc est. In consectetur et lacus ut semper.

Morbi dui enim, pretium ut laoreet vel, dignissim at dolor. Vivamus posuere tortor in mattis pharetra. Ut sollicitudin laoreet consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec consequat sem quis suscipit volutpat. In eget scelerisque tortor. Ut erat neque, malesuada eu commodo in, sollicitudin nec risus. Aliquam ac consectetur enim, ac rhoncus nisi. Suspendisse iaculis leo ac consequat adipiscing. Sed varius laoreet neque et lacinia. Duis ornare sem eu diam adipiscing molestie. Aenean vel auctor mi. Nunc nisi magna, fermentum sit amet consequat imperdiet, consectetur ac turpis. Suspendisse a mauris malesuada, suscipit nisi sit amet, eleifend elit. Ut nulla eros, cursus vel faucibus sed, bibendum ut tortor. Cras accumsan fringilla est vitae aliquet.

Etiam facilisis, erat at sodales placerat, purus arcu vehicula quam, sit amet dignissim neque tellus quis eros. Nunc in ante at neque scelerisque ornare. Proin molestie metus quam, quis consectetur erat malesuada vel. Nullam tempor arcu a dolor pellentesque mollis. Aenean vehicula mauris vel faucibus varius. Nam et hendrerit dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc sit amet orci sed neque tristique lobortis. Nunc sit amet mi non orci consequat rhoncus id nec urna. Sed mauris leo, pretium vitae lacus eget, porttitor ultrices turpis. Fusce augue purus, consequat dapibus convallis condimentum, dignissim in magna.

Etiam pellentesque tellus nisl, ac euismod neque tempus malesuada. Phasellus fringilla dolor eget lorem imperdiet feugiat. Maecenas est lectus, blandit a lectus vel, tristique lacinia mauris. In nulla urna, facilisis id leo vel, auctor condimentum nisi. Vivamus gravida, nunc vitae egestas tincidunt, ante libero luctus velit, id luctus velit lectus ut urna. Morbi molestie erat eget est interdum, nec suscipit elit imperdiet. Duis consequat, ligula sit amet laoreet auctor, ante nulla convallis tortor, ac pretium ipsum nisl ac massa. Vivamus accumsan faucibus bibendum. Praesent non ipsum sed augue facilisis pellentesque pharetra sit amet dui. Proin porta nunc ullamcorper arcu pharetra condimentum. Aenean quis laoreet orci. Quisque hendrerit pharetra urna in interdum.

Praesent rhoncus leo nec orci mattis, vel posuere justo commodo. Fusce nec massa sed est hendrerit aliquet et feugiat ligula. Aenean tempus tortor nec nisi dictum, et placerat quam ultrices. In a vehicula mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin bibendum elit non volutpat venenatis. Sed pharetra ante eu suscipit posuere. Aliquam ligula quam, condimentum eget est adipiscing, dictum aliquet dolor. Integer in imperdiet sapien, quis faucibus mauris. Praesent eget facilisis urna. Quisque elementum sapien dapibus diam sollicitudin, ac eleifend orci fermentum. Phasellus at neque pulvinar, pulvinar quam sed, tincidunt turpis. Nulla odio dui, pharetra non libero a, gravida convallis turpis.

Donec placerat elit vitae nisi imperdiet iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse nec eleifend ipsum. Nam suscipit neque at diam fringilla sagittis. Vivamus ligula augue, eleifend eu pharetra at, tempus a urna. Proin porttitor gravida metus, et interdum augue lacinia quis. Curabitur id posuere mi. Proin sit amet pharetra justo, ut imperdiet tortor.

Etiam tempus velit eu dolor rutrum, vitae consectetur lorem gravida. Nunc ut sagittis quam. Vestibulum eu tincidunt felis, a semper elit. Maecenas dignissim leo venenatis, euismod lorem id, cursus magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt nisi a lectus sollicitudin tempor. Morbi congue est enim, ac aliquam metus cursus ut. Pellentesque hendrerit molestie blandit. Curabitur dapibus pharetra neque sit amet dictum. Proin volutpat lectus non sapien feugiat ultricies. Sed luctus justo sodales urna accumsan, ac volutpat massa auctor. Vestibulum pellentesque justo ac odio mollis consectetur. In et lacus tellus. Proin sagittis pretium diam vitae auctor. Praesent sed libero interdum, accumsan lorem ac, facilisis odio. Aenean scelerisque enim urna, nec placerat orci laoreet nec.

Phasellus sodales adipiscing congue. Nulla lacinia tempor viverra. Suspendisse id semper velit. Donec dapibus semper libero, quis mattis urna dictum ac. Donec sed elit nec dui ultricies accumsan. Suspendisse vitae laoreet lacus, vel ultricies odio. Vivamus in lectus nec ipsum viverra vestibulum. Fusce a urna sit amet urna egestas commodo a sit amet quam. Nam lobortis, lectus vitae vulputate viverra, leo purus pulvinar felis, nec aliquet elit lectus vel diam. Integer egestas diam faucibus felis tempor, eget auctor leo pretium.

Nulla id nibh a lacus scelerisque pharetra. Morbi tempus suscipit libero. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In molestie felis urna, vitae scelerisque neque imperdiet nec. Aliquam condimentum gravida placerat. Curabitur ut pellentesque velit. Cras ultrices malesuada nisi, in gravida nisl faucibus quis. Donec ornare ipsum mauris, congue volutpat sem pretium non. Nunc egestas lacus non lectus consequat, ut tristique urna porttitor. Quisque sed purus ut odio pretium tempor. Vivamus aliquet felis convallis sem auctor, vitae lacinia sapien dictum. Sed tempor auctor mauris, at tincidunt mi porta id. Phasellus nunc risus, ullamcorper in tincidunt et, condimentum sit amet lacus. Proin sagittis arcu eu arcu sagittis tincidunt.

Etiam vel fermentum felis, sed euismod metus. Morbi arcu dolor, ornare luctus molestie sit amet, sodales vel tellus. Fusce mattis nibh vitae nisl luctus euismod. Vivamus sed aliquam ante. Donec orci nisi, faucibus eu consequat nec, commodo ac nibh. Sed quis pharetra tortor, sit amet rhoncus felis. Donec fringilla arcu nec pulvinar elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis ut ipsum et velit venenatis malesuada at ut diam. Aenean porttitor ultricies accumsan. Sed mollis congue elit, id bibendum mi rutrum sit amet. Etiam a erat a nisl suscipit eleifend. In fringilla nisl ipsum, at vulputate augue tempus quis. Vivamus varius ipsum vel tortor posuere, a euismod est rhoncus. Nulla eleifend dignissim tellus at fermentum. Sed sodales consequat orci, a adipiscing purus elementum ac.

Phasellus sagittis massa vitae lectus pharetra laoreet. In aliquet orci vel nunc congue, in molestie ante mattis. Nulla vestibulum ipsum sit amet euismod blandit. Praesent eros velit, convallis vel purus in, mollis feugiat neque. Curabitur libero orci, cursus et auctor in, vulputate vitae est. Nam sollicitudin tellus vitae eros consequat lacinia a quis lectus. Praesent et orci eros. Integer adipiscing urna vitae orci egestas molestie. Mauris volutpat nibh et gravida hendrerit. Nam a nibh a tortor eleifend condimentum elementum sed dolor. Ut lacinia eu justo eu egestas. Fusce commodo, libero at scelerisque posuere, dui dui dapibus magna, vehicula euismod nulla diam vitae justo. Morbi tempor, odio non convallis rhoncus, eros lacus aliquam massa, eget eleifend nisi sapien quis felis. Nunc dolor justo, iaculis eget leo ut, sagittis sagittis mi. Duis pretium euismod nisl. Ut sed neque ante.

Donec nec felis nulla. In in mi purus. Suspendisse diam nisi, laoreet vitae sapien a, sodales auctor magna. Fusce posuere ultrices est, vitae auctor magna cursus quis. Nam eget consectetur est. Pellentesque laoreet nec risus vitae rhoncus. Ut vitae leo scelerisque, pellentesque velit vel, auctor tellus.

**Comment by marty-b** [comment]
Reproduced on prod (https://soylentnews.org/).  This appears to be a bug in the base slashcode.

**Comment by paulej72** [comment]
The code uses the var users_bio_length or if not set 1024.  Should change the the bio text to use the var or 1024 if not set.  users_bio_length is currently set to 1024. Do we want the value change?

**Comment by paulej72** [comment]
Fixed in #57
