### ISSUE TITLE
Polls are not working (on dev)

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#52]
1.) Launched dev and logged on as martyb (https://dev.soylentnews.org/)
2.) Launched 'Poll' from the admin bar: https://dev.soylentnews.org/pollBooth.pl?op=edit
3.) Filled in fields:
a.) The poll: What is your favorite character?
b.) Poll section: Main Page
c.) Poll Topic /dev/random
d.) Poll Type: SlashBox Section Poll
e.) Poll Time: 2015-05-23 00:00:00
f.) The Answers:
Yogi Bear
Fred Flintstone
George Jetson
Wyle E Coyote
Pink Panther
Bugs Bunny
4.) Clicked on 'preview' button
5.) Poll looked okay in the slashbox on the right-hand side:
What is your favorite character?
    Yogi Bear
    Fred Flintstone
    George Jetson
    Wyle E Coyote
    Pink Panther
    Bugs Bunny
    Popeye
6.) Clicked on 'save' button.
7.) Saw confirmation displayed:

Poll Saved
(Poll not yet active.)

    Yogi Bear (0)
    Fred Flintstone (0)
    George Jetson (0)
    Wyle E Coyote (0)
    Pink Panther (0)
    Bugs Bunny (0)
    Popeye (0)

(Poll is closed.)
[ Results | Polls ]
Comments:0 | Votes:

8.) Waited.  Poll never appeared on the main page.  Suspect it may have to do with Nexus implementation?

**Comment by paulej72** [comment]
Fixed in #55
