### ISSUE TITLE
RFE: Story editor enhancement; s|<br>\s*<br>|</p>\n\n<p>| 

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#60]
I have seen stories come into the submissions queue with varying ways of indicating a new paragraph.  I would appreciate it if each new paragraph were preceded with an empty line, and a consistent tag were employed throughout.

Something along these lines would be a huge improvement:
 s|&lt;br&gt;\s*&lt;br&gt;|&lt;/p&gt;\n\n&lt;p&gt;|

(Many thanks to Landon for the code snippet)

**Comment by paulej72** [comment]
fixed in Pull #67
