### ISSUE TITLE
RFE: Automagically insert <p>More after the break... in story text when Extended Copy is NOT NULL

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#61]
When a story is 'long' we include introductory story text in 'Intro Copy' and put the rest into 'Extended Copy'.  When the story is published to the main page, there is currently no indication that there is more to the story than just the 'Intro Copy' text.  Editors have been including text to the effect of:
   &lt;p&gt;[More after the break...]
to inform the reader that there is more to the story.

But, when the user clicks on the story link, the user sees:
1) Intro Copy
2.) More after the break...
3.) Extended Copy

In THIS case, item 2 should NOT be displayed.  Would prefer to see the system automagically include the '[More after the break...'] only when needed.

**Comment by paulej72** [comment]
There be voodoo here.
I mean it.  I can't figure out how the bodytext is not loaded on the homepage.  It almost seems like it is not loaded into the stories in the first place.  If that is the case, it makes it hard to check the bodytext length.

Need to look into this some more.

**Comment by TheMightyBuzzard** [comment]
paulej72 already did this a while back unless I'm mistaken.
