### ISSUE TITLE
Can create new account but cannot login to it

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#63]
1.) Launched dev: https://dev.soylentnews.org/
2.) Clicked "Log Out" in slashbox: Navigation -&gt; You
3.) Clicked Create Account
4.) Entered nick I wanted and entered e-mail address twice
5.) Submitted
6.) Clicked on "Login"
7.) Cut-and-pasted nick and password from e-mail message
8.) Got "Danger Will Robinson..." msg -- could not log into this account
9.) Logged in as martyb (I have privs on the site)
10.) Opened user info page for the just-created user
11.) Clicked on the Password tab
12.) Clicked on 'Reset Password' button
13.) Logged out of martyb
14.) Tried to login using the new nick and the password from the reset e-mail; success.
NOTE: This was a confirmation of behavior that janrinock and I experienced yesterday on dev.  First try - cannot login; reset password and then can login.

**Comment by marty-b** [comment]
NB: The first attempt which revealed this problem was while janrinok was trying to create nick 'dummy1' with uid 4040; the above-documented attempt was while I (martyb) was trying to create nick 'NCommanderTaco' with uid 4041.

**Comment by paulej72** [comment]
Fixed in #69
