### ISSUE TITLE
HR and SMALL tags stripped from story text on dev

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#64]
1.) Logged in as martyb on dev: https://dev.soylentnews.org/
2.) Clicked Submit Story
3.) Entered story text, clicked 'preview', and then submit
4.) Opened submissions queue and selected the just-created submission
5.) At the end of the story, entered our usual 'disclaimer' of late:
&lt;hr&gt;&lt;small&gt;&lt;a href="https://dev.soylentnews.org/submit.pl?op=viewsub&subid=1294"&gt;Original Submission&gt;&lt;/small&gt;
6.) Clicked 'preview'
7.) Saw the HR and SMALL tags removed from the story text.
8.) Clicked 'Update'
9.) Edited the story, entered another copy of the above Original Sub text and clicked 'update' *without* clicking on 'preview', system still stripped the HR and SMALL tags.
10.) These tags work on the production server running the pre-rehash version of the site.

**Comment by marty-b** [comment]
Here is a link to the story: https://dev.soylentnews.org/article.pl?sid=15/05/31/1249203

**Comment by paulej72** [comment]
approvedtags_admin was set in the vars db and was not set to the full list that is defaulted in MySQL.db.  removed var via direct db delete.
