### ISSUE TITLE
Setting the theme to "site default" doesn't actually do that ...

### ISSUE THREAD

**Issue by NCommander** [SoylentNews/rehash#7]
Now that nexuses are (mostly) working, a way to clear out user themes is probably a good idea, as well as perhaps setting a theme on a per nexus basis.

**Comment by paulej72** [comment]
I am thinking we should let the users select themes, but make the nexus name part of the header so that no matter what theme you use, you would instantly know you were on Meta.

**Comment by paulej72** [comment]
working on a fix that puts a banner at the top of the page below slogan.

**Comment by paulej72** [comment]
Fixed in Pull #21.  Themes are now divorced from nexuses (even though they are both skins).  The new banner lets a user know what section they are in better than a theme change.  Also allows user to still keep there preferred theme.
