### ISSUE TITLE
RSS feed with bad links

### ISSUE THREAD

**Issue by GDXN** [SoylentNews/rehash#73]
The links in the RSS feed start with "//soylentnews.org" instead of "htps://soylentnews.org" making some standalone RSS app like QuiteRSS to don't process the links. I wget the rss feed to test if it was the APP or the feed, confirming the error in the feed.

**Comment by SiKing** [comment]
I see all the RSS links as https://soylentnews.org// All of them go to just the main page.

**Comment by paulej72** [comment]
fixed.  skins table urls need to have a protocol set for rss to be happy.  Also we have not gone to dynamic rss yet so rss files are real files that slashd generates.

**Comment by paulej72** [comment]
another bug.  rss link in footer shows as http://soylentnews.org/meta/meta.rss, but i do not currently rewrite the urls on rss files so the file is 404.  it is available at http://soylentnews.org/meta.rss.  should we rewrite the url on the fly or set the link differently?

**Comment by paulej72** [comment]
Fixed in #101
