### ISSUE TITLE
login from https://soylentnews.org slashbox sends user to non-https page where user is not logged in

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#76]
NOTE: This is from memory; steps performed on my mobile phone.
1.) Logged out of https://soylentnews.org
2.) Saw https://soylentnews.org load
3.) Entered userid and password in the 'Login' slashbox
4.) Clicked Login button
5.) Saw the 'login' link still listed in the 'Navigation' slashbox.
6.) Looked more closely and noticed that I was now on 'http' instead of 'https'
7.) Changed browser address to https://soylentnews.org and now saw that I *was* logged in.
8.) This seems *very* familiar.  I seem to recall our having encountered a similar problem something like 8-12 months ago.  When logged onto the site using https and loading a page on the site using http, the code would fail to load the cookie and the user would appear logged out.  Same for the reverse; when logged onto the site using http and loading an https link on the site, the code would also fail to load the cookie and the user would appear logged out.

**Comment by paulej72** [comment]
will be fixed when we make https default

**Comment by paulej72** [comment]
switched to full https. this should now be moot.
