### ISSUE TITLE
Blocks and slashboxes isses (default blocks need to be updated)

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#77]
1.) User: bytram (4043) had the slashbox option for showing 'Most Recent Journal Entries' (MRJE) selected in the user preferences.  This was LONG before the site was upgraded to rehash.
2.) Loading the main page does NOT show the MRJE slashbox.
3.) I saw the same issue when logged in as user martyb (76) shortly after the site loaded rehash.  In this case, however, I went in and noticed that my selections had been all reset (cleared).  I reselected the ones I wanted and saved them.  I *do* see the MRJE slashbox when logged in as that user.
NOTE: scenario with user bytram observed using my mobile phone's web browser; scenario with user martyb observed using Pale Moon on Windows.

**Comment by paulej72** [comment]
Fix for this is in #74.  This had to do with some differences in how data was stored in the skin field of the blocks table.  Also updated the blocks table data, (but not the files yet).

**Comment by paulej72** [comment]
Some blocks are not set to show on all nexues, and probably should.  Not sure we need any nexus specific blocks.

The issue with the default blocks is that they are tied to the default skins that we killed off.  We should probably redo the default skins and blocks to match up well with what we are doing. Add in meta for example.

**Comment by paulej72** [comment]
Fixed in #202
