### ISSUE TITLE
Have stopped receiving 'SoylentNews Daily Newsletter' after cut over to rehash

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#85]
1.) Background: users stdin (3487) FoolTimeJob (3488) had their preferences set to e-mail the 'SoylentNews Daily Newsletter'. i.e.:
   Daily Newsletter: [E-mail]
2.) Last-received newsletter was on 2015-05-31 which was the last day before we cut over to running rehash.
3.) Have not yet tried to see if a user who selected this AFTER the cutover is or is not receiving the newsletter.
4.) May also apply to 'Daily Headlines', but these users were not set up to receive those, so cannot speak to that one.

**Comment by paulej72** [comment]
strange emails are getting sent on dev, I wonder what is up?

**Comment by paulej72** [comment]
From the slashd log
>Thu Jun  4 02:00:13 2015 [daily.pl] Cannot decode string with wide characters at /srv/soylentnews.org/perl/lib/perl5/site_perl/5.20.1/x86_64-linux-thread-multi/Encode.pm line 244.

**Comment by paulej72** [comment]
fixed in #101.  html2text was decoding utf8 and it was no longer needed.
