### ISSUE TITLE
Memcahed is no longer working

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#87]
1.) Was viewing story: https://soylentnews.org/article.pl?sid=15/06/04/0235239
2.) Noticed moderation choices drop-down list box contained no words.
3.) Viewed source in browser.
4.) Scrolled down to a representative example, for comment #192042
5.) Saw this code snippet for the moderation choices:<pre>
&lt;select id="reason_192042" name="reason_192042"&gt;
	&lt;option value="HASH(0x6c64f70)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8863e20)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x88ecbd8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x6c529e8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x88b73f8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x87b3398)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8fc9370)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x90a8cf8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8017580)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8812410)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7f3f4d8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x84ccef8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8f07bd8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8f9d1b8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8e04468)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8fea920)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8849788)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8826be0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x905d420)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x902f338)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x88111f0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x88729f8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8d84a28)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8d82df0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8f9f638)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x88c35d0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x82569f0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x9016d78)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x88c8ee0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8edeb90)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8f9e3b8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x84cc760)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8812998)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x904fd68)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x904eb70)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x888a940)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x774d350)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x84b60a8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x6c17720)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8e66380)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8fd4f58)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x88919a0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x891ece0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7f3d8e8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8387808)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x9021ae0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x88290f8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7f3d960)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x885f950)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x884f6f8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x908a488)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7f61ba8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7f01450)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8f9f5d8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x890e318)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x905fc50)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x887f458)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7f41b20)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x904f7b8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x904eca8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8e03a78)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x87b0ea0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x83419d0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8d818d8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8fe5af0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x88a8cb0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7f629e8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8de0718)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8387a30)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x90a9b00)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8e663c8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x73d8cf0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7f61cf8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x77369b8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7fb6aa8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8872e00)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8d82b68)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x9056ec0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8d8a878)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7f41ec8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8e236b8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x88220f8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8387070)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x6c8da18)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8feaa88)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x825ea48)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8893030)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x904e930)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8864658)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x880fda0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8822368)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8350e60)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8feac50)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x90a2070)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8811928)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x7f412a0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x884fc20)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8ea30b8)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x9021990)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x8f9e2b0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x87a5a88)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x83877c0)"&gt;&lt;/option&gt;
	&lt;option value="HASH(0x87a37f8)"&gt;&lt;/option&gt;
&lt;/select&gt;
</pre>
6.) Hit F5 to refresh page in browser (Pale Moon) and saw 'normal' moderation choices displayed.

**Comment by paulej72** [comment]
Think it has something to do with rehash on fluorine needing a double restart to clear up certain stuff.  When I went to this article I got a rehash error and no comments.  After a reload of the page all was well, and I did not see the bad hash info.  I restarted rehash just in case as I had did a deploy earlier this morning.

**Comment by paulej72** [comment]
due to memcached bug.

**Comment by TheMightyBuzzard** [comment]
Memcached is disabled on prod and dev. I successfully reimplemented using redis rather than memcached but saw zero improvement, so there's no reason to pursue this further at this point. Closing.
