### ISSUE TITLE
comment filter should be respective to the summary

### ISSUE THREAD

**Issue by GravisZro** [SoylentNews/rehash#88]
i quoted part of a summary and got snagged by the comment filter.

this summary https://soylentnews.org/article.pl?sid=15/06/05/0311212 mentions "Viagra and Cialis" and guess what just so happens to be on the "YOU MAY NOT POST THAT!!! >:(((("-list?

as a result i had to redact the quote and reword my comment: https://soylentnews.org/comments.pl?sid=7791&cid=192471

**Comment by paulej72** [comment]
The current filters were put in place because the site was getting spammed with drug comments and submissions.  Having the filters bypass stuff in blockquotes would be a way to bypass the filter.  I am not sure if we want to do that.

**Comment by paulej72** [comment]
Probably should put a disable switch on the filters so they are easy to trun on and off.

**Comment by GravisZro** [comment]
seems like you should have a rule that if the person has made X number of posts and not been banned, that spam related filters would no longer apply.  might encourage people to actually register.
