### ISSUE TITLE
HSTS header for HTTPS connections

### ISSUE THREAD

**Issue by tomascassidy** [SoylentNews/rehash#93]
After reading the post on switching to all HTTPS, I noticed that soylentnews is not sending any HSTS header.  Can this get added in to the server config for HTTPS connections? You wouldn't want it set for any non-HTTPS connections like TOR.

**Comment by NCommander** [comment]
I want to do thus and plan on enabling it with certificate pinning but the
HSTS header would prevent us from disabling SSL in case something else goes
wrong. We'll have a serious discussion on enabling it a few week from now.

**Comment by tomascassidy** [comment]
No worries.  Just making sure it's on your radar.  Thanks for being proactive on this stuff.

**Comment by TheMightyBuzzard** [comment]
We're doing this now. Closing.
