### ISSUE TITLE
Daily Digest Emails not being delivered

### ISSUE THREAD

**Issue by juggs** [SoylentNews/rehash#95]
From SoyCow5891 in IRC..

<i>hello, I just noticed I am not receiving my daily digest in my inbox anymore (since 31-5), has this happend to anyone else? I checked my preferences on the site.. they were not changed.. and set to send the email.?</i>

I am seeing no digests either but I am seeing mails
Subject: [SoylentNews] slashd Error Alert
Body: SoylentNews Slashd Error Alert!
SLASHD line 165 produced the following error:
daily.pl odd exit (status 25, signal 0)

Daily digest, daily.pl - I guess that's related right? :D That's the limit of my logic ability at this time :dancer:

OK - I put a 'dancer' in - I have no idea what that is... don't get too distracted!

**Comment by JamesWrigley** [comment]
This is also happening to me, haven't received any digests since 31/05.

**Comment by aikomastboom** [comment]
as I was too lazy to actually log into irc.. for the record. I am SoyCow5891

**Comment by paulej72** [comment]
Known issue, see #85
