### ISSUE TITLE
Use of Unordered List during editing causes text corruptions

### ISSUE THREAD

**Issue by janrinok** [SoylentNews/rehash#99]
During the editing of a submission, if an unordered list (ul) is entered and the document is subsequently previewed, the text and html around the list is badly corrupted.  Additional html tags are entered (including ordered list, paragraph and unnecessary additional unordered list tags) plus apparently random parentheses and '|' characters.

During a quick test of 2 stories, the corruption did not occur during a save to the story queue - only when previewing any editing completed so far.

**Comment by paulej72** [comment]
See #145

**Comment by paulej72** [comment]
could not replicate.  Not sure what is up.  It it takyon's script?

**Comment by paulej72** [comment]
yep takyon's script had a regex bug.  See https://soylentnews.org/comments.pl?sid=7657&cid=196128.
